<?php

function get_ionicons()
{
    $icons = array(
        array('value' => 'ion-alert', 'content' => '&#xf101; Alert'),
        array('value' => 'ion-alert-circled', 'content' => '&#xf100; Alert Circled'),
        array('value' => 'ion-android-add', 'content' => '&#xf2c7; Android Add'),
        array('value' => 'ion-android-add-circle', 'content' => '&#xf359; Android Add Circle'),
        array('value' => 'ion-android-alarm-clock', 'content' => '&#xf35a; Android Alarm Clock'),
        array('value' => 'ion-android-alert', 'content' => '&#xf35b; Android Alert'),
        array('value' => 'ion-android-apps', 'content' => '&#xf35c; Android Apps'),
        array('value' => 'ion-android-archive', 'content' => '&#xf2c9; Android Archive'),
        array('value' => 'ion-android-arrow-back', 'content' => '&#xf2ca; Android Arrow Back'),
        array('value' => 'ion-android-arrow-down', 'content' => '&#xf35d; Android Arrow Down'),
        array('value' => 'ion-android-arrow-dropdown', 'content' => '&#xf35f; Android Arrow Dropdown'),
        array('value' => 'ion-android-arrow-dropdown-circle', 'content' => '&#xf35e; Android Arrow Dropdown Circle'),
        array('value' => 'ion-android-arrow-dropleft', 'content' => '&#xf361; Android Arrow Dropleft'),
        array('value' => 'ion-android-arrow-dropleft-circle', 'content' => '&#xf360; Android Arrow Dropleft Circle'),
        array('value' => 'ion-android-arrow-dropright', 'content' => '&#xf363; Android Arrow Dropright'),
        array('value' => 'ion-android-arrow-dropright-circle', 'content' => '&#xf362; Android Arrow Dropright Circle'),
        array('value' => 'ion-android-arrow-dropup', 'content' => '&#xf365; Android Arrow Dropup'),
        array('value' => 'ion-android-arrow-dropup-circle', 'content' => '&#xf364; Android Arrow Dropup Circle'),
        array('value' => 'ion-android-arrow-forward', 'content' => '&#xf30f; Android Arrow Forward'),
        array('value' => 'ion-android-arrow-up', 'content' => '&#xf366; Android Arrow Up'),
        array('value' => 'ion-android-attach', 'content' => '&#xf367; Android Attach'),
        array('value' => 'ion-android-bar', 'content' => '&#xf368; Android Bar'),
        array('value' => 'ion-android-bicycle', 'content' => '&#xf369; Android Bicycle'),
        array('value' => 'ion-android-boat', 'content' => '&#xf36a; Android Boat'),
        array('value' => 'ion-android-bookmark', 'content' => '&#xf36b; Android Bookmark'),
        array('value' => 'ion-android-bulb', 'content' => '&#xf36c; Android Bulb'),
        array('value' => 'ion-android-bus', 'content' => '&#xf36d; Android Bus'),
        array('value' => 'ion-android-calendar', 'content' => '&#xf2d1; Android Calendar'),
        array('value' => 'ion-android-call', 'content' => '&#xf2d2; Android Call'),
        array('value' => 'ion-android-camera', 'content' => '&#xf2d3; Android Camera'),
        array('value' => 'ion-android-cancel', 'content' => '&#xf36e; Android Cancel'),
        array('value' => 'ion-android-car', 'content' => '&#xf36f; Android Car'),
        array('value' => 'ion-android-cart', 'content' => '&#xf370; Android Cart'),
        array('value' => 'ion-android-chat', 'content' => '&#xf2d4; Android Chat'),
        array('value' => 'ion-android-checkbox', 'content' => '&#xf374; Android Checkbox'),
        array('value' => 'ion-android-checkbox-blank', 'content' => '&#xf371; Android Checkbox Blank'),
        array('value' => 'ion-android-checkbox-outline', 'content' => '&#xf373; Android Checkbox Outline'),
        array('value' => 'ion-android-checkbox-outline-blank', 'content' => '&#xf372; Android Checkbox Outline Blank'),
        array('value' => 'ion-android-checkmark-circle', 'content' => '&#xf375; Android Checkmark Circle'),
        array('value' => 'ion-android-clipboard', 'content' => '&#xf376; Android Clipboard'),
        array('value' => 'ion-android-close', 'content' => '&#xf2d7; Android Close'),
        array('value' => 'ion-android-cloud', 'content' => '&#xf37a; Android Cloud'),
        array('value' => 'ion-android-cloud-circle', 'content' => '&#xf377; Android Cloud Circle'),
        array('value' => 'ion-android-cloud-done', 'content' => '&#xf378; Android Cloud Done'),
        array('value' => 'ion-android-cloud-outline', 'content' => '&#xf379; Android Cloud Outline'),
        array('value' => 'ion-android-color-palette', 'content' => '&#xf37b; Android Color Palette'),
        array('value' => 'ion-android-compass', 'content' => '&#xf37c; Android Compass'),
        array('value' => 'ion-android-contact', 'content' => '&#xf2d8; Android Contact'),
        array('value' => 'ion-android-contacts', 'content' => '&#xf2d9; Android Contacts'),
        array('value' => 'ion-android-contract', 'content' => '&#xf37d; Android Contract'),
        array('value' => 'ion-android-create', 'content' => '&#xf37e; Android Create'),
        array('value' => 'ion-android-delete', 'content' => '&#xf37f; Android Delete'),
        array('value' => 'ion-android-desktop', 'content' => '&#xf380; Android Desktop'),
        array('value' => 'ion-android-document', 'content' => '&#xf381; Android Document'),
        array('value' => 'ion-android-done', 'content' => '&#xf383; Android Done'),
        array('value' => 'ion-android-done-all', 'content' => '&#xf382; Android Done All'),
        array('value' => 'ion-android-download', 'content' => '&#xf2dd; Android Download'),
        array('value' => 'ion-android-drafts', 'content' => '&#xf384; Android Drafts'),
        array('value' => 'ion-android-exit', 'content' => '&#xf385; Android Exit'),
        array('value' => 'ion-android-expand', 'content' => '&#xf386; Android Expand'),
        array('value' => 'ion-android-favorite', 'content' => '&#xf388; Android Favorite'),
        array('value' => 'ion-android-favorite-outline', 'content' => '&#xf387; Android Favorite Outline'),
        array('value' => 'ion-android-film', 'content' => '&#xf389; Android Film'),
        array('value' => 'ion-android-folder', 'content' => '&#xf2e0; Android Folder'),
        array('value' => 'ion-android-folder-open', 'content' => '&#xf38a; Android Folder Open'),
        array('value' => 'ion-android-funnel', 'content' => '&#xf38b; Android Funnel'),
        array('value' => 'ion-android-globe', 'content' => '&#xf38c; Android Globe'),
        array('value' => 'ion-android-hand', 'content' => '&#xf2e3; Android Hand'),
        array('value' => 'ion-android-hangout', 'content' => '&#xf38d; Android Hangout'),
        array('value' => 'ion-android-happy', 'content' => '&#xf38e; Android Happy'),
        array('value' => 'ion-android-home', 'content' => '&#xf38f; Android Home'),
        array('value' => 'ion-android-image', 'content' => '&#xf2e4; Android Image'),
        array('value' => 'ion-android-laptop', 'content' => '&#xf390; Android Laptop'),
        array('value' => 'ion-android-list', 'content' => '&#xf391; Android List'),
        array('value' => 'ion-android-locate', 'content' => '&#xf2e9; Android Locate'),
        array('value' => 'ion-android-lock', 'content' => '&#xf392; Android Lock'),
        array('value' => 'ion-android-mail', 'content' => '&#xf2eb; Android Mail'),
        array('value' => 'ion-android-map', 'content' => '&#xf393; Android Map'),
        array('value' => 'ion-android-menu', 'content' => '&#xf394; Android Menu'),
        array('value' => 'ion-android-microphone', 'content' => '&#xf2ec; Android Microphone'),
        array('value' => 'ion-android-microphone-off', 'content' => '&#xf395; Android Microphone Off'),
        array('value' => 'ion-android-more-horizontal', 'content' => '&#xf396; Android More Horizontal'),
        array('value' => 'ion-android-more-vertical', 'content' => '&#xf397; Android More Vertical'),
        array('value' => 'ion-android-navigate', 'content' => '&#xf398; Android Navigate'),
        array('value' => 'ion-android-notifications', 'content' => '&#xf39b; Android Notifications'),
        array('value' => 'ion-android-notifications-none', 'content' => '&#xf399; Android Notifications None'),
        array('value' => 'ion-android-notifications-off', 'content' => '&#xf39a; Android Notifications Off'),
        array('value' => 'ion-android-open', 'content' => '&#xf39c; Android Open'),
        array('value' => 'ion-android-options', 'content' => '&#xf39d; Android Options'),
        array('value' => 'ion-android-people', 'content' => '&#xf39e; Android People'),
        array('value' => 'ion-android-person', 'content' => '&#xf3a0; Android Person'),
        array('value' => 'ion-android-person-add', 'content' => '&#xf39f; Android Person Add'),
        array('value' => 'ion-android-phone-landscape', 'content' => '&#xf3a1; Android Phone Landscape'),
        array('value' => 'ion-android-phone-portrait', 'content' => '&#xf3a2; Android Phone Portrait'),
        array('value' => 'ion-android-pin', 'content' => '&#xf3a3; Android Pin'),
        array('value' => 'ion-android-plane', 'content' => '&#xf3a4; Android Plane'),
        array('value' => 'ion-android-playstore', 'content' => '&#xf2f0; Android Playstore'),
        array('value' => 'ion-android-print', 'content' => '&#xf3a5; Android Print'),
        array('value' => 'ion-android-radio-button-off', 'content' => '&#xf3a6; Android Radio Button Off'),
        array('value' => 'ion-android-radio-button-on', 'content' => '&#xf3a7; Android Radio Button On'),
        array('value' => 'ion-android-refresh', 'content' => '&#xf3a8; Android Refresh'),
        array('value' => 'ion-android-remove', 'content' => '&#xf2f4; Android Remove'),
        array('value' => 'ion-android-remove-circle', 'content' => '&#xf3a9; Android Remove Circle'),
        array('value' => 'ion-android-restaurant', 'content' => '&#xf3aa; Android Restaurant'),
        array('value' => 'ion-android-sad', 'content' => '&#xf3ab; Android Sad'),
        array('value' => 'ion-android-search', 'content' => '&#xf2f5; Android Search'),
        array('value' => 'ion-android-send', 'content' => '&#xf2f6; Android Send'),
        array('value' => 'ion-android-settings', 'content' => '&#xf2f7; Android Settings'),
        array('value' => 'ion-android-share', 'content' => '&#xf2f8; Android Share'),
        array('value' => 'ion-android-share-alt', 'content' => '&#xf3ac; Android Share Alt'),
        array('value' => 'ion-android-star', 'content' => '&#xf2fc; Android Star'),
        array('value' => 'ion-android-star-half', 'content' => '&#xf3ad; Android Star Half'),
        array('value' => 'ion-android-star-outline', 'content' => '&#xf3ae; Android Star Outline'),
        array('value' => 'ion-android-stopwatch', 'content' => '&#xf2fd; Android Stopwatch'),
        array('value' => 'ion-android-subway', 'content' => '&#xf3af; Android Subway'),
        array('value' => 'ion-android-sunny', 'content' => '&#xf3b0; Android Sunny'),
        array('value' => 'ion-android-sync', 'content' => '&#xf3b1; Android Sync'),
        array('value' => 'ion-android-textsms', 'content' => '&#xf3b2; Android Textsms'),
        array('value' => 'ion-android-time', 'content' => '&#xf3b3; Android Time'),
        array('value' => 'ion-android-train', 'content' => '&#xf3b4; Android Train'),
        array('value' => 'ion-android-unlock', 'content' => '&#xf3b5; Android Unlock'),
        array('value' => 'ion-android-upload', 'content' => '&#xf3b6; Android Upload'),
        array('value' => 'ion-android-volume-down', 'content' => '&#xf3b7; Android Volume Down'),
        array('value' => 'ion-android-volume-mute', 'content' => '&#xf3b8; Android Volume Mute'),
        array('value' => 'ion-android-volume-off', 'content' => '&#xf3b9; Android Volume Off'),
        array('value' => 'ion-android-volume-up', 'content' => '&#xf3ba; Android Volume Up'),
        array('value' => 'ion-android-walk', 'content' => '&#xf3bb; Android Walk'),
        array('value' => 'ion-android-warning', 'content' => '&#xf3bc; Android Warning'),
        array('value' => 'ion-android-watch', 'content' => '&#xf3bd; Android Watch'),
        array('value' => 'ion-android-wifi', 'content' => '&#xf305; Android Wifi'),
        array('value' => 'ion-aperture', 'content' => '&#xf313; Aperture'),
        array('value' => 'ion-archive', 'content' => '&#xf102; Archive'),
        array('value' => 'ion-arrow-down-a', 'content' => '&#xf103; Arrow Down A'),
        array('value' => 'ion-arrow-down-b', 'content' => '&#xf104; Arrow Down B'),
        array('value' => 'ion-arrow-down-c', 'content' => '&#xf105; Arrow Down C'),
        array('value' => 'ion-arrow-expand', 'content' => '&#xf25e; Arrow Expand'),
        array('value' => 'ion-arrow-graph-down-left', 'content' => '&#xf25f; Arrow Graph Down Left'),
        array('value' => 'ion-arrow-graph-down-right', 'content' => '&#xf260; Arrow Graph Down Right'),
        array('value' => 'ion-arrow-graph-up-left', 'content' => '&#xf261; Arrow Graph Up Left'),
        array('value' => 'ion-arrow-graph-up-right', 'content' => '&#xf262; Arrow Graph Up Right'),
        array('value' => 'ion-arrow-left-a', 'content' => '&#xf106; Arrow Left A'),
        array('value' => 'ion-arrow-left-b', 'content' => '&#xf107; Arrow Left B'),
        array('value' => 'ion-arrow-left-c', 'content' => '&#xf108; Arrow Left C'),
        array('value' => 'ion-arrow-move', 'content' => '&#xf263; Arrow Move'),
        array('value' => 'ion-arrow-resize', 'content' => '&#xf264; Arrow Resize'),
        array('value' => 'ion-arrow-return-left', 'content' => '&#xf265; Arrow Return Left'),
        array('value' => 'ion-arrow-return-right', 'content' => '&#xf266; Arrow Return Right'),
        array('value' => 'ion-arrow-right-a', 'content' => '&#xf109; Arrow Right A'),
        array('value' => 'ion-arrow-right-b', 'content' => '&#xf10a; Arrow Right B'),
        array('value' => 'ion-arrow-right-c', 'content' => '&#xf10b; Arrow Right C'),
        array('value' => 'ion-arrow-shrink', 'content' => '&#xf267; Arrow Shrink'),
        array('value' => 'ion-arrow-swap', 'content' => '&#xf268; Arrow Swap'),
        array('value' => 'ion-arrow-up-a', 'content' => '&#xf10c; Arrow Up A'),
        array('value' => 'ion-arrow-up-b', 'content' => '&#xf10d; Arrow Up B'),
        array('value' => 'ion-arrow-up-c', 'content' => '&#xf10e; Arrow Up C'),
        array('value' => 'ion-asterisk', 'content' => '&#xf314; Asterisk'),
        array('value' => 'ion-at', 'content' => '&#xf10f; At'),
        array('value' => 'ion-backspace', 'content' => '&#xf3bf; Backspace'),
        array('value' => 'ion-backspace-outline', 'content' => '&#xf3be; Backspace Outline'),
        array('value' => 'ion-bag', 'content' => '&#xf110; Bag'),
        array('value' => 'ion-battery-charging', 'content' => '&#xf111; Battery Charging'),
        array('value' => 'ion-battery-empty', 'content' => '&#xf112; Battery Empty'),
        array('value' => 'ion-battery-full', 'content' => '&#xf113; Battery Full'),
        array('value' => 'ion-battery-half', 'content' => '&#xf114; Battery Half'),
        array('value' => 'ion-battery-low', 'content' => '&#xf115; Battery Low'),
        array('value' => 'ion-beaker', 'content' => '&#xf269; Beaker'),
        array('value' => 'ion-beer', 'content' => '&#xf26a; Beer'),
        array('value' => 'ion-bluetooth', 'content' => '&#xf116; Bluetooth'),
        array('value' => 'ion-bonfire', 'content' => '&#xf315; Bonfire'),
        array('value' => 'ion-bookmark', 'content' => '&#xf26b; Bookmark'),
        array('value' => 'ion-bowtie', 'content' => '&#xf3c0; Bowtie'),
        array('value' => 'ion-briefcase', 'content' => '&#xf26c; Briefcase'),
        array('value' => 'ion-bug', 'content' => '&#xf2be; Bug'),
        array('value' => 'ion-calculator', 'content' => '&#xf26d; Calculator'),
        array('value' => 'ion-calendar', 'content' => '&#xf117; Calendar'),
        array('value' => 'ion-camera', 'content' => '&#xf118; Camera'),
        array('value' => 'ion-card', 'content' => '&#xf119; Card'),
        array('value' => 'ion-cash', 'content' => '&#xf316; Cash'),
        array('value' => 'ion-chatbox', 'content' => '&#xf11b; Chatbox'),
        array('value' => 'ion-chatbox-working', 'content' => '&#xf11a; Chatbox Working'),
        array('value' => 'ion-chatboxes', 'content' => '&#xf11c; Chatboxes'),
        array('value' => 'ion-chatbubble', 'content' => '&#xf11e; Chatbubble'),
        array('value' => 'ion-chatbubble-working', 'content' => '&#xf11d; Chatbubble Working'),
        array('value' => 'ion-chatbubbles', 'content' => '&#xf11f; Chatbubbles'),
        array('value' => 'ion-checkmark', 'content' => '&#xf122; Checkmark'),
        array('value' => 'ion-checkmark-circled', 'content' => '&#xf120; Checkmark Circled'),
        array('value' => 'ion-checkmark-round', 'content' => '&#xf121; Checkmark Round'),
        array('value' => 'ion-chevron-down', 'content' => '&#xf123; Chevron Down'),
        array('value' => 'ion-chevron-left', 'content' => '&#xf124; Chevron Left'),
        array('value' => 'ion-chevron-right', 'content' => '&#xf125; Chevron Right'),
        array('value' => 'ion-chevron-up', 'content' => '&#xf126; Chevron Up'),
        array('value' => 'ion-clipboard', 'content' => '&#xf127; Clipboard'),
        array('value' => 'ion-clock', 'content' => '&#xf26e; Clock'),
        array('value' => 'ion-close', 'content' => '&#xf12a; Close'),
        array('value' => 'ion-close-circled', 'content' => '&#xf128; Close Circled'),
        array('value' => 'ion-close-round', 'content' => '&#xf129; Close Round'),
        array('value' => 'ion-closed-captioning', 'content' => '&#xf317; Closed Captioning'),
        array('value' => 'ion-cloud', 'content' => '&#xf12b; Cloud'),
        array('value' => 'ion-code', 'content' => '&#xf271; Code'),
        array('value' => 'ion-code-download', 'content' => '&#xf26f; Code Download'),
        array('value' => 'ion-code-working', 'content' => '&#xf270; Code Working'),
        array('value' => 'ion-coffee', 'content' => '&#xf272; Coffee'),
        array('value' => 'ion-compass', 'content' => '&#xf273; Compass'),
        array('value' => 'ion-compose', 'content' => '&#xf12c; Compose'),
        array('value' => 'ion-connection-bars', 'content' => '&#xf274; Connectbars'),
        array('value' => 'ion-contrast', 'content' => '&#xf275; Contrast'),
        array('value' => 'ion-crop', 'content' => '&#xf3c1; Crop'),
        array('value' => 'ion-cube', 'content' => '&#xf318; Cube'),
        array('value' => 'ion-disc', 'content' => '&#xf12d; Disc'),
        array('value' => 'ion-document', 'content' => '&#xf12f; Document'),
        array('value' => 'ion-document-text', 'content' => '&#xf12e; Document Text'),
        array('value' => 'ion-drag', 'content' => '&#xf130; Drag'),
        array('value' => 'ion-earth', 'content' => '&#xf276; Earth'),
        array('value' => 'ion-easel', 'content' => '&#xf3c2; Easel'),
        array('value' => 'ion-edit', 'content' => '&#xf2bf; Edit'),
        array('value' => 'ion-egg', 'content' => '&#xf277; Egg'),
        array('value' => 'ion-eject', 'content' => '&#xf131; Eject'),
        array('value' => 'ion-email', 'content' => '&#xf132; Email'),
        array('value' => 'ion-email-unread', 'content' => '&#xf3c3; Email Unread'),
        array('value' => 'ion-erlenmeyer-flask', 'content' => '&#xf3c5; Erlenmeyer Flask'),
        array('value' => 'ion-erlenmeyer-flask-bubbles', 'content' => '&#xf3c4; Erlenmeyer Flask Bubbles'),
        array('value' => 'ion-eye', 'content' => '&#xf133; Eye'),
        array('value' => 'ion-eye-disabled', 'content' => '&#xf306; Eye Disabled'),
        array('value' => 'ion-female', 'content' => '&#xf278; Female'),
        array('value' => 'ion-filing', 'content' => '&#xf134; Filing'),
        array('value' => 'ion-film-marker', 'content' => '&#xf135; Film Marker'),
        array('value' => 'ion-fireball', 'content' => '&#xf319; Fireball'),
        array('value' => 'ion-flag', 'content' => '&#xf279; Flag'),
        array('value' => 'ion-flame', 'content' => '&#xf31a; Flame'),
        array('value' => 'ion-flash', 'content' => '&#xf137; Flash'),
        array('value' => 'ion-flash-off', 'content' => '&#xf136; Flash Off'),
        array('value' => 'ion-folder', 'content' => '&#xf139; Folder'),
        array('value' => 'ion-fork', 'content' => '&#xf27a; Fork'),
        array('value' => 'ion-fork-repo', 'content' => '&#xf2c0; Fork Repo'),
        array('value' => 'ion-forward', 'content' => '&#xf13a; Forward'),
        array('value' => 'ion-funnel', 'content' => '&#xf31b; Funnel'),
        array('value' => 'ion-gear-a', 'content' => '&#xf13d; Gear A'),
        array('value' => 'ion-gear-b', 'content' => '&#xf13e; Gear B'),
        array('value' => 'ion-grid', 'content' => '&#xf13f; Grid'),
        array('value' => 'ion-hammer', 'content' => '&#xf27b; Hammer'),
        array('value' => 'ion-happy', 'content' => '&#xf31c; Happy'),
        array('value' => 'ion-happy-outline', 'content' => '&#xf3c6; Happy Outline'),
        array('value' => 'ion-headphone', 'content' => '&#xf140; Headphone'),
        array('value' => 'ion-heart', 'content' => '&#xf141; Heart'),
        array('value' => 'ion-heart-broken', 'content' => '&#xf31d; Heart Broken'),
        array('value' => 'ion-help', 'content' => '&#xf143; Help'),
        array('value' => 'ion-help-buoy', 'content' => '&#xf27c; Help Buoy'),
        array('value' => 'ion-help-circled', 'content' => '&#xf142; Help Circled'),
        array('value' => 'ion-home', 'content' => '&#xf144; Home'),
        array('value' => 'ion-icecream', 'content' => '&#xf27d; Icecream'),
        array('value' => 'ion-image', 'content' => '&#xf147; Image'),
        array('value' => 'ion-images', 'content' => '&#xf148; Images'),
        array('value' => 'ion-information', 'content' => '&#xf14a; Information'),
        array('value' => 'ion-information-circled', 'content' => '&#xf149; Informatcircled'),
        array('value' => 'ion-ionic', 'content' => '&#xf14b; Ionic'),
        array('value' => 'ion-ios-alarm', 'content' => '&#xf3c8; Ios Alarm'),
        array('value' => 'ion-ios-alarm-outline', 'content' => '&#xf3c7; Ios Alarm Outline'),
        array('value' => 'ion-ios-albums', 'content' => '&#xf3ca; Ios Albums'),
        array('value' => 'ion-ios-albums-outline', 'content' => '&#xf3c9; Ios Albums Outline'),
        array('value' => 'ion-ios-americanfootball', 'content' => '&#xf3cc; Ios Americanfootball'),
        array('value' => 'ion-ios-americanfootball-outline', 'content' => '&#xf3cb; Ios Americanfootball Outline'),
        array('value' => 'ion-ios-analytics', 'content' => '&#xf3ce; Ios Analytics'),
        array('value' => 'ion-ios-analytics-outline', 'content' => '&#xf3cd; Ios Analytics Outline'),
        array('value' => 'ion-ios-arrow-back', 'content' => '&#xf3cf; Ios Arrow Back'),
        array('value' => 'ion-ios-arrow-down', 'content' => '&#xf3d0; Ios Arrow Down'),
        array('value' => 'ion-ios-arrow-forward', 'content' => '&#xf3d1; Ios Arrow Forward'),
        array('value' => 'ion-ios-arrow-left', 'content' => '&#xf3d2; Ios Arrow Left'),
        array('value' => 'ion-ios-arrow-right', 'content' => '&#xf3d3; Ios Arrow Right'),
        array('value' => 'ion-ios-arrow-thin-down', 'content' => '&#xf3d4; Ios Arrow Thin Down'),
        array('value' => 'ion-ios-arrow-thin-left', 'content' => '&#xf3d5; Ios Arrow Thin Left'),
        array('value' => 'ion-ios-arrow-thin-right', 'content' => '&#xf3d6; Ios Arrow Thin Right'),
        array('value' => 'ion-ios-arrow-thin-up', 'content' => '&#xf3d7; Ios Arrow Thin Up'),
        array('value' => 'ion-ios-arrow-up', 'content' => '&#xf3d8; Ios Arrow Up'),
        array('value' => 'ion-ios-at', 'content' => '&#xf3da; Ios At'),
        array('value' => 'ion-ios-at-outline', 'content' => '&#xf3d9; Ios At Outline'),
        array('value' => 'ion-ios-barcode', 'content' => '&#xf3dc; Ios Barcode'),
        array('value' => 'ion-ios-barcode-outline', 'content' => '&#xf3db; Ios Barcode Outline'),
        array('value' => 'ion-ios-baseball', 'content' => '&#xf3de; Ios Baseball'),
        array('value' => 'ion-ios-baseball-outline', 'content' => '&#xf3dd; Ios Baseball Outline'),
        array('value' => 'ion-ios-basketball', 'content' => '&#xf3e0; Ios Basketball'),
        array('value' => 'ion-ios-basketball-outline', 'content' => '&#xf3df; Ios Basketball Outline'),
        array('value' => 'ion-ios-bell', 'content' => '&#xf3e2; Ios Bell'),
        array('value' => 'ion-ios-bell-outline', 'content' => '&#xf3e1; Ios Bell Outline'),
        array('value' => 'ion-ios-body', 'content' => '&#xf3e4; Ios Body'),
        array('value' => 'ion-ios-body-outline', 'content' => '&#xf3e3; Ios Body Outline'),
        array('value' => 'ion-ios-bolt', 'content' => '&#xf3e6; Ios Bolt'),
        array('value' => 'ion-ios-bolt-outline', 'content' => '&#xf3e5; Ios Bolt Outline'),
        array('value' => 'ion-ios-book', 'content' => '&#xf3e8; Ios Book'),
        array('value' => 'ion-ios-book-outline', 'content' => '&#xf3e7; Ios Book Outline'),
        array('value' => 'ion-ios-bookmarks', 'content' => '&#xf3ea; Ios Bookmarks'),
        array('value' => 'ion-ios-bookmarks-outline', 'content' => '&#xf3e9; Ios Bookmarks Outline'),
        array('value' => 'ion-ios-box', 'content' => '&#xf3ec; Ios Box'),
        array('value' => 'ion-ios-box-outline', 'content' => '&#xf3eb; Ios Box Outline'),
        array('value' => 'ion-ios-briefcase', 'content' => '&#xf3ee; Ios Briefcase'),
        array('value' => 'ion-ios-briefcase-outline', 'content' => '&#xf3ed; Ios Briefcase Outline'),
        array('value' => 'ion-ios-browsers', 'content' => '&#xf3f0; Ios Browsers'),
        array('value' => 'ion-ios-browsers-outline', 'content' => '&#xf3ef; Ios Browsers Outline'),
        array('value' => 'ion-ios-calculator', 'content' => '&#xf3f2; Ios Calculator'),
        array('value' => 'ion-ios-calculator-outline', 'content' => '&#xf3f1; Ios Calculator Outline'),
        array('value' => 'ion-ios-calendar', 'content' => '&#xf3f4; Ios Calendar'),
        array('value' => 'ion-ios-calendar-outline', 'content' => '&#xf3f3; Ios Calendar Outline'),
        array('value' => 'ion-ios-camera', 'content' => '&#xf3f6; Ios Camera'),
        array('value' => 'ion-ios-camera-outline', 'content' => '&#xf3f5; Ios Camera Outline'),
        array('value' => 'ion-ios-cart', 'content' => '&#xf3f8; Ios Cart'),
        array('value' => 'ion-ios-cart-outline', 'content' => '&#xf3f7; Ios Cart Outline'),
        array('value' => 'ion-ios-chatboxes', 'content' => '&#xf3fa; Ios Chatboxes'),
        array('value' => 'ion-ios-chatboxes-outline', 'content' => '&#xf3f9; Ios Chatboxes Outline'),
        array('value' => 'ion-ios-chatbubble', 'content' => '&#xf3fc; Ios Chatbubble'),
        array('value' => 'ion-ios-chatbubble-outline', 'content' => '&#xf3fb; Ios Chatbubble Outline'),
        array('value' => 'ion-ios-checkmark', 'content' => '&#xf3ff; Ios Checkmark'),
        array('value' => 'ion-ios-checkmark-empty', 'content' => '&#xf3fd; Ios Checkmark Empty'),
        array('value' => 'ion-ios-checkmark-outline', 'content' => '&#xf3fe; Ios Checkmark Outline'),
        array('value' => 'ion-ios-circle-filled', 'content' => '&#xf400; Ios Circle Filled'),
        array('value' => 'ion-ios-circle-outline', 'content' => '&#xf401; Ios Circle Outline'),
        array('value' => 'ion-ios-clock', 'content' => '&#xf403; Ios Clock'),
        array('value' => 'ion-ios-clock-outline', 'content' => '&#xf402; Ios Clock Outline'),
        array('value' => 'ion-ios-close', 'content' => '&#xf406; Ios Close'),
        array('value' => 'ion-ios-close-empty', 'content' => '&#xf404; Ios Close Empty'),
        array('value' => 'ion-ios-close-outline', 'content' => '&#xf405; Ios Close Outline'),
        array('value' => 'ion-ios-cloud', 'content' => '&#xf40c; Ios Cloud'),
        array('value' => 'ion-ios-cloud-download', 'content' => '&#xf408; Ios Cloud Download'),
        array('value' => 'ion-ios-cloud-download-outline', 'content' => '&#xf407; Ios Cloud Download Outline'),
        array('value' => 'ion-ios-cloud-outline', 'content' => '&#xf409; Ios Cloud Outline'),
        array('value' => 'ion-ios-cloud-upload', 'content' => '&#xf40b; Ios Cloud Upload'),
        array('value' => 'ion-ios-cloud-upload-outline', 'content' => '&#xf40a; Ios Cloud Upload Outline'),
        array('value' => 'ion-ios-cloudy', 'content' => '&#xf410; Ios Cloudy'),
        array('value' => 'ion-ios-cloudy-night', 'content' => '&#xf40e; Ios Cloudy Night'),
        array('value' => 'ion-ios-cloudy-night-outline', 'content' => '&#xf40d; Ios Cloudy Night Outline'),
        array('value' => 'ion-ios-cloudy-outline', 'content' => '&#xf40f; Ios Cloudy Outline'),
        array('value' => 'ion-ios-cog', 'content' => '&#xf412; Ios Cog'),
        array('value' => 'ion-ios-cog-outline', 'content' => '&#xf411; Ios Cog Outline'),
        array('value' => 'ion-ios-color-filter', 'content' => '&#xf414; Ios Color Filter'),
        array('value' => 'ion-ios-color-filter-outline', 'content' => '&#xf413; Ios Color Filter Outline'),
        array('value' => 'ion-ios-color-wand', 'content' => '&#xf416; Ios Color Wand'),
        array('value' => 'ion-ios-color-wand-outline', 'content' => '&#xf415; Ios Color Wand Outline'),
        array('value' => 'ion-ios-compose', 'content' => '&#xf418; Ios Compose'),
        array('value' => 'ion-ios-compose-outline', 'content' => '&#xf417; Ios Compose Outline'),
        array('value' => 'ion-ios-contact', 'content' => '&#xf41a; Ios Contact'),
        array('value' => 'ion-ios-contact-outline', 'content' => '&#xf419; Ios Contact Outline'),
        array('value' => 'ion-ios-copy', 'content' => '&#xf41c; Ios Copy'),
        array('value' => 'ion-ios-copy-outline', 'content' => '&#xf41b; Ios Copy Outline'),
        array('value' => 'ion-ios-crop', 'content' => '&#xf41e; Ios Crop'),
        array('value' => 'ion-ios-crop-strong', 'content' => '&#xf41d; Ios Crop Strong'),
        array('value' => 'ion-ios-download', 'content' => '&#xf420; Ios Download'),
        array('value' => 'ion-ios-download-outline', 'content' => '&#xf41f; Ios Download Outline'),
        array('value' => 'ion-ios-drag', 'content' => '&#xf421; Ios Drag'),
        array('value' => 'ion-ios-email', 'content' => '&#xf423; Ios Email'),
        array('value' => 'ion-ios-email-outline', 'content' => '&#xf422; Ios Email Outline'),
        array('value' => 'ion-ios-eye', 'content' => '&#xf425; Ios Eye'),
        array('value' => 'ion-ios-eye-outline', 'content' => '&#xf424; Ios Eye Outline'),
        array('value' => 'ion-ios-fastforward', 'content' => '&#xf427; Ios Fastforward'),
        array('value' => 'ion-ios-fastforward-outline', 'content' => '&#xf426; Ios Fastforward Outline'),
        array('value' => 'ion-ios-filing', 'content' => '&#xf429; Ios Filing'),
        array('value' => 'ion-ios-filing-outline', 'content' => '&#xf428; Ios Filing Outline'),
        array('value' => 'ion-ios-film', 'content' => '&#xf42b; Ios Film'),
        array('value' => 'ion-ios-film-outline', 'content' => '&#xf42a; Ios Film Outline'),
        array('value' => 'ion-ios-flag', 'content' => '&#xf42d; Ios Flag'),
        array('value' => 'ion-ios-flag-outline', 'content' => '&#xf42c; Ios Flag Outline'),
        array('value' => 'ion-ios-flame', 'content' => '&#xf42f; Ios Flame'),
        array('value' => 'ion-ios-flame-outline', 'content' => '&#xf42e; Ios Flame Outline'),
        array('value' => 'ion-ios-flask', 'content' => '&#xf431; Ios Flask'),
        array('value' => 'ion-ios-flask-outline', 'content' => '&#xf430; Ios Flask Outline'),
        array('value' => 'ion-ios-flower', 'content' => '&#xf433; Ios Flower'),
        array('value' => 'ion-ios-flower-outline', 'content' => '&#xf432; Ios Flower Outline'),
        array('value' => 'ion-ios-folder', 'content' => '&#xf435; Ios Folder'),
        array('value' => 'ion-ios-folder-outline', 'content' => '&#xf434; Ios Folder Outline'),
        array('value' => 'ion-ios-football', 'content' => '&#xf437; Ios Football'),
        array('value' => 'ion-ios-football-outline', 'content' => '&#xf436; Ios Football Outline'),
        array('value' => 'ion-ios-game-controller-a', 'content' => '&#xf439; Ios Game Controller A'),
        array('value' => 'ion-ios-game-controller-a-outline', 'content' => '&#xf438; Ios Game Controller A Outline'),
        array('value' => 'ion-ios-game-controller-b', 'content' => '&#xf43b; Ios Game Controller B'),
        array('value' => 'ion-ios-game-controller-b-outline', 'content' => '&#xf43a; Ios Game Controller B Outline'),
        array('value' => 'ion-ios-gear', 'content' => '&#xf43d; Ios Gear'),
        array('value' => 'ion-ios-gear-outline', 'content' => '&#xf43c; Ios Gear Outline'),
        array('value' => 'ion-ios-glasses', 'content' => '&#xf43f; Ios Glasses'),
        array('value' => 'ion-ios-glasses-outline', 'content' => '&#xf43e; Ios Glasses Outline'),
        array('value' => 'ion-ios-grid-view', 'content' => '&#xf441; Ios Grid View'),
        array('value' => 'ion-ios-grid-view-outline', 'content' => '&#xf440; Ios Grid View Outline'),
        array('value' => 'ion-ios-heart', 'content' => '&#xf443; Ios Heart'),
        array('value' => 'ion-ios-heart-outline', 'content' => '&#xf442; Ios Heart Outline'),
        array('value' => 'ion-ios-help', 'content' => '&#xf446; Ios Help'),
        array('value' => 'ion-ios-help-empty', 'content' => '&#xf444; Ios Help Empty'),
        array('value' => 'ion-ios-help-outline', 'content' => '&#xf445; Ios Help Outline'),
        array('value' => 'ion-ios-home', 'content' => '&#xf448; Ios Home'),
        array('value' => 'ion-ios-home-outline', 'content' => '&#xf447; Ios Home Outline'),
        array('value' => 'ion-ios-infinite', 'content' => '&#xf44a; Ios Infinite'),
        array('value' => 'ion-ios-infinite-outline', 'content' => '&#xf449; Ios Infinite Outline'),
        array('value' => 'ion-ios-information', 'content' => '&#xf44d; Ios Information'),
        array('value' => 'ion-ios-information-empty', 'content' => '&#xf44b; Ios Informatempty'),
        array('value' => 'ion-ios-information-outline', 'content' => '&#xf44c; Ios Informatoutline'),
        array('value' => 'ion-ios-ionic-outline', 'content' => '&#xf44e; Ios Ionic Outline'),
        array('value' => 'ion-ios-keypad', 'content' => '&#xf450; Ios Keypad'),
        array('value' => 'ion-ios-keypad-outline', 'content' => '&#xf44f; Ios Keypad Outline'),
        array('value' => 'ion-ios-lightbulb', 'content' => '&#xf452; Ios Lightbulb'),
        array('value' => 'ion-ios-lightbulb-outline', 'content' => '&#xf451; Ios Lightbulb Outline'),
        array('value' => 'ion-ios-list', 'content' => '&#xf454; Ios List'),
        array('value' => 'ion-ios-list-outline', 'content' => '&#xf453; Ios List Outline'),
        array('value' => 'ion-ios-location', 'content' => '&#xf456; Ios Location'),
        array('value' => 'ion-ios-location-outline', 'content' => '&#xf455; Ios Locatoutline'),
        array('value' => 'ion-ios-locked', 'content' => '&#xf458; Ios Locked'),
        array('value' => 'ion-ios-locked-outline', 'content' => '&#xf457; Ios Locked Outline'),
        array('value' => 'ion-ios-loop', 'content' => '&#xf45a; Ios Loop'),
        array('value' => 'ion-ios-loop-strong', 'content' => '&#xf459; Ios Loop Strong'),
        array('value' => 'ion-ios-medical', 'content' => '&#xf45c; Ios Medical'),
        array('value' => 'ion-ios-medical-outline', 'content' => '&#xf45b; Ios Medical Outline'),
        array('value' => 'ion-ios-medkit', 'content' => '&#xf45e; Ios Medkit'),
        array('value' => 'ion-ios-medkit-outline', 'content' => '&#xf45d; Ios Medkit Outline'),
        array('value' => 'ion-ios-mic', 'content' => '&#xf461; Ios Mic'),
        array('value' => 'ion-ios-mic-off', 'content' => '&#xf45f; Ios Mic Off'),
        array('value' => 'ion-ios-mic-outline', 'content' => '&#xf460; Ios Mic Outline'),
        array('value' => 'ion-ios-minus', 'content' => '&#xf464; Ios Minus'),
        array('value' => 'ion-ios-minus-empty', 'content' => '&#xf462; Ios Minus Empty'),
        array('value' => 'ion-ios-minus-outline', 'content' => '&#xf463; Ios Minus Outline'),
        array('value' => 'ion-ios-monitor', 'content' => '&#xf466; Ios Monitor'),
        array('value' => 'ion-ios-monitor-outline', 'content' => '&#xf465; Ios Monitor Outline'),
        array('value' => 'ion-ios-moon', 'content' => '&#xf468; Ios Moon'),
        array('value' => 'ion-ios-moon-outline', 'content' => '&#xf467; Ios Moon Outline'),
        array('value' => 'ion-ios-more', 'content' => '&#xf46a; Ios More'),
        array('value' => 'ion-ios-more-outline', 'content' => '&#xf469; Ios More Outline'),
        array('value' => 'ion-ios-musical-note', 'content' => '&#xf46b; Ios Musical Note'),
        array('value' => 'ion-ios-musical-notes', 'content' => '&#xf46c; Ios Musical Notes'),
        array('value' => 'ion-ios-navigate', 'content' => '&#xf46e; Ios Navigate'),
        array('value' => 'ion-ios-navigate-outline', 'content' => '&#xf46d; Ios Navigate Outline'),
        array('value' => 'ion-ios-nutrition', 'content' => '&#xf470; Ios Nutrition'),
        array('value' => 'ion-ios-nutrition-outline', 'content' => '&#xf46f; Ios Nutritoutline'),
        array('value' => 'ion-ios-paper', 'content' => '&#xf472; Ios Paper'),
        array('value' => 'ion-ios-paper-outline', 'content' => '&#xf471; Ios Paper Outline'),
        array('value' => 'ion-ios-paperplane', 'content' => '&#xf474; Ios Paperplane'),
        array('value' => 'ion-ios-paperplane-outline', 'content' => '&#xf473; Ios Paperplane Outline'),
        array('value' => 'ion-ios-partlysunny', 'content' => '&#xf476; Ios Partlysunny'),
        array('value' => 'ion-ios-partlysunny-outline', 'content' => '&#xf475; Ios Partlysunny Outline'),
        array('value' => 'ion-ios-pause', 'content' => '&#xf478; Ios Pause'),
        array('value' => 'ion-ios-pause-outline', 'content' => '&#xf477; Ios Pause Outline'),
        array('value' => 'ion-ios-paw', 'content' => '&#xf47a; Ios Paw'),
        array('value' => 'ion-ios-paw-outline', 'content' => '&#xf479; Ios Paw Outline'),
        array('value' => 'ion-ios-people', 'content' => '&#xf47c; Ios People'),
        array('value' => 'ion-ios-people-outline', 'content' => '&#xf47b; Ios People Outline'),
        array('value' => 'ion-ios-person', 'content' => '&#xf47e; Ios Person'),
        array('value' => 'ion-ios-person-outline', 'content' => '&#xf47d; Ios Person Outline'),
        array('value' => 'ion-ios-personadd', 'content' => '&#xf480; Ios Personadd'),
        array('value' => 'ion-ios-personadd-outline', 'content' => '&#xf47f; Ios Personadd Outline'),
        array('value' => 'ion-ios-photos', 'content' => '&#xf482; Ios Photos'),
        array('value' => 'ion-ios-photos-outline', 'content' => '&#xf481; Ios Photos Outline'),
        array('value' => 'ion-ios-pie', 'content' => '&#xf484; Ios Pie'),
        array('value' => 'ion-ios-pie-outline', 'content' => '&#xf483; Ios Pie Outline'),
        array('value' => 'ion-ios-pint', 'content' => '&#xf486; Ios Pint'),
        array('value' => 'ion-ios-pint-outline', 'content' => '&#xf485; Ios Pint Outline'),
        array('value' => 'ion-ios-play', 'content' => '&#xf488; Ios Play'),
        array('value' => 'ion-ios-play-outline', 'content' => '&#xf487; Ios Play Outline'),
        array('value' => 'ion-ios-plus', 'content' => '&#xf48b; Ios Plus'),
        array('value' => 'ion-ios-plus-empty', 'content' => '&#xf489; Ios Plus Empty'),
        array('value' => 'ion-ios-plus-outline', 'content' => '&#xf48a; Ios Plus Outline'),
        array('value' => 'ion-ios-pricetag', 'content' => '&#xf48d; Ios Pricetag'),
        array('value' => 'ion-ios-pricetag-outline', 'content' => '&#xf48c; Ios Pricetag Outline'),
        array('value' => 'ion-ios-pricetags', 'content' => '&#xf48f; Ios Pricetags'),
        array('value' => 'ion-ios-pricetags-outline', 'content' => '&#xf48e; Ios Pricetags Outline'),
        array('value' => 'ion-ios-printer', 'content' => '&#xf491; Ios Printer'),
        array('value' => 'ion-ios-printer-outline', 'content' => '&#xf490; Ios Printer Outline'),
        array('value' => 'ion-ios-pulse', 'content' => '&#xf493; Ios Pulse'),
        array('value' => 'ion-ios-pulse-strong', 'content' => '&#xf492; Ios Pulse Strong'),
        array('value' => 'ion-ios-rainy', 'content' => '&#xf495; Ios Rainy'),
        array('value' => 'ion-ios-rainy-outline', 'content' => '&#xf494; Ios Rainy Outline'),
        array('value' => 'ion-ios-recording', 'content' => '&#xf497; Ios Recording'),
        array('value' => 'ion-ios-recording-outline', 'content' => '&#xf496; Ios Recording Outline'),
        array('value' => 'ion-ios-redo', 'content' => '&#xf499; Ios Redo'),
        array('value' => 'ion-ios-redo-outline', 'content' => '&#xf498; Ios Redo Outline'),
        array('value' => 'ion-ios-refresh', 'content' => '&#xf49c; Ios Refresh'),
        array('value' => 'ion-ios-refresh-empty', 'content' => '&#xf49a; Ios Refresh Empty'),
        array('value' => 'ion-ios-refresh-outline', 'content' => '&#xf49b; Ios Refresh Outline'),
        array('value' => 'ion-ios-reload', 'content' => '&#xf49d; Ios Reload'),
        array('value' => 'ion-ios-reverse-camera', 'content' => '&#xf49f; Ios Reverse Camera'),
        array('value' => 'ion-ios-reverse-camera-outline', 'content' => '&#xf49e; Ios Reverse Camera Outline'),
        array('value' => 'ion-ios-rewind', 'content' => '&#xf4a1; Ios Rewind'),
        array('value' => 'ion-ios-rewind-outline', 'content' => '&#xf4a0; Ios Rewind Outline'),
        array('value' => 'ion-ios-rose', 'content' => '&#xf4a3; Ios Rose'),
        array('value' => 'ion-ios-rose-outline', 'content' => '&#xf4a2; Ios Rose Outline'),
        array('value' => 'ion-ios-search', 'content' => '&#xf4a5; Ios Search'),
        array('value' => 'ion-ios-search-strong', 'content' => '&#xf4a4; Ios Search Strong'),
        array('value' => 'ion-ios-settings', 'content' => '&#xf4a7; Ios Settings'),
        array('value' => 'ion-ios-settings-strong', 'content' => '&#xf4a6; Ios Settings Strong'),
        array('value' => 'ion-ios-shuffle', 'content' => '&#xf4a9; Ios Shuffle'),
        array('value' => 'ion-ios-shuffle-strong', 'content' => '&#xf4a8; Ios Shuffle Strong'),
        array('value' => 'ion-ios-skipbackward', 'content' => '&#xf4ab; Ios Skipbackward'),
        array('value' => 'ion-ios-skipbackward-outline', 'content' => '&#xf4aa; Ios Skipbackward Outline'),
        array('value' => 'ion-ios-skipforward', 'content' => '&#xf4ad; Ios Skipforward'),
        array('value' => 'ion-ios-skipforward-outline', 'content' => '&#xf4ac; Ios Skipforward Outline'),
        array('value' => 'ion-ios-snowy', 'content' => '&#xf4ae; Ios Snowy'),
        array('value' => 'ion-ios-speedometer', 'content' => '&#xf4b0; Ios Speedometer'),
        array('value' => 'ion-ios-speedometer-outline', 'content' => '&#xf4af; Ios Speedometer Outline'),
        array('value' => 'ion-ios-star', 'content' => '&#xf4b3; Ios Star'),
        array('value' => 'ion-ios-star-half', 'content' => '&#xf4b1; Ios Star Half'),
        array('value' => 'ion-ios-star-outline', 'content' => '&#xf4b2; Ios Star Outline'),
        array('value' => 'ion-ios-stopwatch', 'content' => '&#xf4b5; Ios Stopwatch'),
        array('value' => 'ion-ios-stopwatch-outline', 'content' => '&#xf4b4; Ios Stopwatch Outline'),
        array('value' => 'ion-ios-sunny', 'content' => '&#xf4b7; Ios Sunny'),
        array('value' => 'ion-ios-sunny-outline', 'content' => '&#xf4b6; Ios Sunny Outline'),
        array('value' => 'ion-ios-telephone', 'content' => '&#xf4b9; Ios Telephone'),
        array('value' => 'ion-ios-telephone-outline', 'content' => '&#xf4b8; Ios Telephone Outline'),
        array('value' => 'ion-ios-tennisball', 'content' => '&#xf4bb; Ios Tennisball'),
        array('value' => 'ion-ios-tennisball-outline', 'content' => '&#xf4ba; Ios Tennisball Outline'),
        array('value' => 'ion-ios-thunderstorm', 'content' => '&#xf4bd; Ios Thunderstorm'),
        array('value' => 'ion-ios-thunderstorm-outline', 'content' => '&#xf4bc; Ios Thunderstorm Outline'),
        array('value' => 'ion-ios-time', 'content' => '&#xf4bf; Ios Time'),
        array('value' => 'ion-ios-time-outline', 'content' => '&#xf4be; Ios Time Outline'),
        array('value' => 'ion-ios-timer', 'content' => '&#xf4c1; Ios Timer'),
        array('value' => 'ion-ios-timer-outline', 'content' => '&#xf4c0; Ios Timer Outline'),
        array('value' => 'ion-ios-toggle', 'content' => '&#xf4c3; Ios Toggle'),
        array('value' => 'ion-ios-toggle-outline', 'content' => '&#xf4c2; Ios Toggle Outline'),
        array('value' => 'ion-ios-trash', 'content' => '&#xf4c5; Ios Trash'),
        array('value' => 'ion-ios-trash-outline', 'content' => '&#xf4c4; Ios Trash Outline'),
        array('value' => 'ion-ios-undo', 'content' => '&#xf4c7; Ios Undo'),
        array('value' => 'ion-ios-undo-outline', 'content' => '&#xf4c6; Ios Undo Outline'),
        array('value' => 'ion-ios-unlocked', 'content' => '&#xf4c9; Ios Unlocked'),
        array('value' => 'ion-ios-unlocked-outline', 'content' => '&#xf4c8; Ios Unlocked Outline'),
        array('value' => 'ion-ios-upload', 'content' => '&#xf4cb; Ios Upload'),
        array('value' => 'ion-ios-upload-outline', 'content' => '&#xf4ca; Ios Upload Outline'),
        array('value' => 'ion-ios-videocam', 'content' => '&#xf4cd; Ios Videocam'),
        array('value' => 'ion-ios-videocam-outline', 'content' => '&#xf4cc; Ios Videocam Outline'),
        array('value' => 'ion-ios-volume-high', 'content' => '&#xf4ce; Ios Volume High'),
        array('value' => 'ion-ios-volume-low', 'content' => '&#xf4cf; Ios Volume Low'),
        array('value' => 'ion-ios-wineglass', 'content' => '&#xf4d1; Ios Wineglass'),
        array('value' => 'ion-ios-wineglass-outline', 'content' => '&#xf4d0; Ios Wineglass Outline'),
        array('value' => 'ion-ios-world', 'content' => '&#xf4d3; Ios World'),
        array('value' => 'ion-ios-world-outline', 'content' => '&#xf4d2; Ios World Outline'),
        array('value' => 'ion-ipad', 'content' => '&#xf1f9; Ipad'),
        array('value' => 'ion-iphone', 'content' => '&#xf1fa; Iphone'),
        array('value' => 'ion-ipod', 'content' => '&#xf1fb; Ipod'),
        array('value' => 'ion-jet', 'content' => '&#xf295; Jet'),
        array('value' => 'ion-key', 'content' => '&#xf296; Key'),
        array('value' => 'ion-knife', 'content' => '&#xf297; Knife'),
        array('value' => 'ion-laptop', 'content' => '&#xf1fc; Laptop'),
        array('value' => 'ion-leaf', 'content' => '&#xf1fd; Leaf'),
        array('value' => 'ion-levels', 'content' => '&#xf298; Levels'),
        array('value' => 'ion-lightbulb', 'content' => '&#xf299; Lightbulb'),
        array('value' => 'ion-link', 'content' => '&#xf1fe; Link'),
        array('value' => 'ion-load-a', 'content' => '&#xf29a; Load A'),
        array('value' => 'ion-load-b', 'content' => '&#xf29b; Load B'),
        array('value' => 'ion-load-c', 'content' => '&#xf29c; Load C'),
        array('value' => 'ion-load-d', 'content' => '&#xf29d; Load D'),
        array('value' => 'ion-location', 'content' => '&#xf1ff; Location'),
        array('value' => 'ion-lock-combination', 'content' => '&#xf4d4; Lock Combination'),
        array('value' => 'ion-locked', 'content' => '&#xf200; Locked'),
        array('value' => 'ion-log-in', 'content' => '&#xf29e; Log In'),
        array('value' => 'ion-log-out', 'content' => '&#xf29f; Log Out'),
        array('value' => 'ion-loop', 'content' => '&#xf201; Loop'),
        array('value' => 'ion-magnet', 'content' => '&#xf2a0; Magnet'),
        array('value' => 'ion-male', 'content' => '&#xf2a1; Male'),
        array('value' => 'ion-man', 'content' => '&#xf202; Man'),
        array('value' => 'ion-map', 'content' => '&#xf203; Map'),
        array('value' => 'ion-medkit', 'content' => '&#xf2a2; Medkit'),
        array('value' => 'ion-merge', 'content' => '&#xf33f; Merge'),
        array('value' => 'ion-mic-a', 'content' => '&#xf204; Mic A'),
        array('value' => 'ion-mic-b', 'content' => '&#xf205; Mic B'),
        array('value' => 'ion-mic-c', 'content' => '&#xf206; Mic C'),
        array('value' => 'ion-minus', 'content' => '&#xf209; Minus'),
        array('value' => 'ion-minus-circled', 'content' => '&#xf207; Minus Circled'),
        array('value' => 'ion-minus-round', 'content' => '&#xf208; Minus Round'),
        array('value' => 'ion-model-s', 'content' => '&#xf2c1; Model S'),
        array('value' => 'ion-monitor', 'content' => '&#xf20a; Monitor'),
        array('value' => 'ion-more', 'content' => '&#xf20b; More'),
        array('value' => 'ion-mouse', 'content' => '&#xf340; Mouse'),
        array('value' => 'ion-music-note', 'content' => '&#xf20c; Music Note'),
        array('value' => 'ion-navicon', 'content' => '&#xf20e; Navicon'),
        array('value' => 'ion-navicon-round', 'content' => '&#xf20d; Navicon Round'),
        array('value' => 'ion-navigate', 'content' => '&#xf2a3; Navigate'),
        array('value' => 'ion-network', 'content' => '&#xf341; Network'),
        array('value' => 'ion-no-smoking', 'content' => '&#xf2c2; No Smoking'),
        array('value' => 'ion-nuclear', 'content' => '&#xf2a4; Nuclear'),
        array('value' => 'ion-outlet', 'content' => '&#xf342; Outlet'),
        array('value' => 'ion-paintbrush', 'content' => '&#xf4d5; Paintbrush'),
        array('value' => 'ion-paintbucket', 'content' => '&#xf4d6; Paintbucket'),
        array('value' => 'ion-paper-airplane', 'content' => '&#xf2c3; Paper Airplane'),
        array('value' => 'ion-paperclip', 'content' => '&#xf20f; Paperclip'),
        array('value' => 'ion-pause', 'content' => '&#xf210; Pause'),
        array('value' => 'ion-person', 'content' => '&#xf213; Person'),
        array('value' => 'ion-person-add', 'content' => '&#xf211; Person Add'),
        array('value' => 'ion-person-stalker', 'content' => '&#xf212; Person Stalker'),
        array('value' => 'ion-pie-graph', 'content' => '&#xf2a5; Pie Graph'),
        array('value' => 'ion-pin', 'content' => '&#xf2a6; Pin'),
        array('value' => 'ion-pinpoint', 'content' => '&#xf2a7; Pinpoint'),
        array('value' => 'ion-pizza', 'content' => '&#xf2a8; Pizza'),
        array('value' => 'ion-plane', 'content' => '&#xf214; Plane'),
        array('value' => 'ion-planet', 'content' => '&#xf343; Planet'),
        array('value' => 'ion-play', 'content' => '&#xf215; Play'),
        array('value' => 'ion-playstation', 'content' => '&#xf30a; Playstation'),
        array('value' => 'ion-plus', 'content' => '&#xf218; Plus'),
        array('value' => 'ion-plus-circled', 'content' => '&#xf216; Plus Circled'),
        array('value' => 'ion-plus-round', 'content' => '&#xf217; Plus Round'),
        array('value' => 'ion-podium', 'content' => '&#xf344; Podium'),
        array('value' => 'ion-pound', 'content' => '&#xf219; Pound'),
        array('value' => 'ion-power', 'content' => '&#xf2a9; Power'),
        array('value' => 'ion-pricetag', 'content' => '&#xf2aa; Pricetag'),
        array('value' => 'ion-pricetags', 'content' => '&#xf2ab; Pricetags'),
        array('value' => 'ion-printer', 'content' => '&#xf21a; Printer'),
        array('value' => 'ion-pull-request', 'content' => '&#xf345; Pull Request'),
        array('value' => 'ion-qr-scanner', 'content' => '&#xf346; Qr Scanner'),
        array('value' => 'ion-quote', 'content' => '&#xf347; Quote'),
        array('value' => 'ion-radio-waves', 'content' => '&#xf2ac; Radio Waves'),
        array('value' => 'ion-record', 'content' => '&#xf21b; Record'),
        array('value' => 'ion-refresh', 'content' => '&#xf21c; Refresh'),
        array('value' => 'ion-reply', 'content' => '&#xf21e; Reply'),
        array('value' => 'ion-reply-all', 'content' => '&#xf21d; Reply All'),
        array('value' => 'ion-ribbon-a', 'content' => '&#xf348; Ribbon A'),
        array('value' => 'ion-ribbon-b', 'content' => '&#xf349; Ribbon B'),
        array('value' => 'ion-sad', 'content' => '&#xf34a; Sad'),
        array('value' => 'ion-sad-outline', 'content' => '&#xf4d7; Sad Outline'),
        array('value' => 'ion-scissors', 'content' => '&#xf34b; Scissors'),
        array('value' => 'ion-search', 'content' => '&#xf21f; Search'),
        array('value' => 'ion-settings', 'content' => '&#xf2ad; Settings'),
        array('value' => 'ion-share', 'content' => '&#xf220; Share'),
        array('value' => 'ion-shuffle', 'content' => '&#xf221; Shuffle'),
        array('value' => 'ion-skip-backward', 'content' => '&#xf222; Skip Backward'),
        array('value' => 'ion-skip-forward', 'content' => '&#xf223; Skip Forward'),
        array('value' => 'ion-social-android', 'content' => '&#xf225; Social Android'),
        array('value' => 'ion-social-android-outline', 'content' => '&#xf224; Social Android Outline'),
        array('value' => 'ion-social-angular', 'content' => '&#xf4d9; Social Angular'),
        array('value' => 'ion-social-angular-outline', 'content' => '&#xf4d8; Social Angular Outline'),
        array('value' => 'ion-social-apple', 'content' => '&#xf227; Social Apple'),
        array('value' => 'ion-social-apple-outline', 'content' => '&#xf226; Social Apple Outline'),
        array('value' => 'ion-social-bitcoin', 'content' => '&#xf2af; Social Bitcoin'),
        array('value' => 'ion-social-bitcoin-outline', 'content' => '&#xf2ae; Social Bitcoin Outline'),
        array('value' => 'ion-social-buffer', 'content' => '&#xf229; Social Buffer'),
        array('value' => 'ion-social-buffer-outline', 'content' => '&#xf228; Social Buffer Outline'),
        array('value' => 'ion-social-chrome', 'content' => '&#xf4db; Social Chrome'),
        array('value' => 'ion-social-chrome-outline', 'content' => '&#xf4da; Social Chrome Outline'),
        array('value' => 'ion-social-codepen', 'content' => '&#xf4dd; Social Codepen'),
        array('value' => 'ion-social-codepen-outline', 'content' => '&#xf4dc; Social Codepen Outline'),
        array('value' => 'ion-social-css3', 'content' => '&#xf4df; Social Css3'),
        array('value' => 'ion-social-css3-outline', 'content' => '&#xf4de; Social Css3 Outline'),
        array('value' => 'ion-social-designernews', 'content' => '&#xf22b; Social Designernews'),
        array('value' => 'ion-social-designernews-outline', 'content' => '&#xf22a; Social Designernews Outline'),
        array('value' => 'ion-social-dropbox', 'content' => '&#xf22f; Social Dropbox'),
        array('value' => 'ion-social-dropbox-outline', 'content' => '&#xf22e; Social Dropbox Outline'),
        array('value' => 'ion-social-euro', 'content' => '&#xf4e1; Social Euro'),
        array('value' => 'ion-social-euro-outline', 'content' => '&#xf4e0; Social Euro Outline'),
        array('value' => 'ion-social-facebook', 'content' => '&#xf231; Social Facebook'),
        array('value' => 'ion-social-facebook-outline', 'content' => '&#xf230; Social Facebook Outline'),
        array('value' => 'ion-social-foursquare', 'content' => '&#xf34d; Social Foursquare'),
        array('value' => 'ion-social-foursquare-outline', 'content' => '&#xf34c; Social Foursquare Outline'),
        array('value' => 'ion-social-freebsd-devil', 'content' => '&#xf2c4; Social Freebsd Devil'),
        array('value' => 'ion-social-github', 'content' => '&#xf233; Social Github'),
        array('value' => 'ion-social-github-outline', 'content' => '&#xf232; Social Github Outline'),
        array('value' => 'ion-social-google', 'content' => '&#xf34f; Social Google'),
        array('value' => 'ion-social-google-outline', 'content' => '&#xf34e; Social Google Outline'),
        array('value' => 'ion-social-googleplus', 'content' => '&#xf235; Social Googleplus'),
        array('value' => 'ion-social-googleplus-outline', 'content' => '&#xf234; Social Googleplus Outline'),
        array('value' => 'ion-social-hackernews', 'content' => '&#xf237; Social Hackernews'),
        array('value' => 'ion-social-hackernews-outline', 'content' => '&#xf236; Social Hackernews Outline'),
        array('value' => 'ion-social-html5', 'content' => '&#xf4e3; Social Html5'),
        array('value' => 'ion-social-html5-outline', 'content' => '&#xf4e2; Social Html5 Outline'),
        array('value' => 'ion-social-instagram', 'content' => '&#xf351; Social Instagram'),
        array('value' => 'ion-social-instagram-outline', 'content' => '&#xf350; Social Instagram Outline'),
        array('value' => 'ion-social-javascript', 'content' => '&#xf4e5; Social Javascript'),
        array('value' => 'ion-social-javascript-outline', 'content' => '&#xf4e4; Social Javascript Outline'),
        array('value' => 'ion-social-linkedin', 'content' => '&#xf239; Social Linkedin'),
        array('value' => 'ion-social-linkedin-outline', 'content' => '&#xf238; Social Linkedin Outline'),
        array('value' => 'ion-social-markdown', 'content' => '&#xf4e6; Social Markdown'),
        array('value' => 'ion-social-nodejs', 'content' => '&#xf4e7; Social Nodejs'),
        array('value' => 'ion-social-octocat', 'content' => '&#xf4e8; Social Octocat'),
        array('value' => 'ion-social-pinterest', 'content' => '&#xf2b1; Social Pinterest'),
        array('value' => 'ion-social-pinterest-outline', 'content' => '&#xf2b0; Social Pinterest Outline'),
        array('value' => 'ion-social-python', 'content' => '&#xf4e9; Social Python'),
        array('value' => 'ion-social-reddit', 'content' => '&#xf23b; Social Reddit'),
        array('value' => 'ion-social-reddit-outline', 'content' => '&#xf23a; Social Reddit Outline'),
        array('value' => 'ion-social-rss', 'content' => '&#xf23d; Social Rss'),
        array('value' => 'ion-social-rss-outline', 'content' => '&#xf23c; Social Rss Outline'),
        array('value' => 'ion-social-sass', 'content' => '&#xf4ea; Social Sass'),
        array('value' => 'ion-social-skype', 'content' => '&#xf23f; Social Skype'),
        array('value' => 'ion-social-skype-outline', 'content' => '&#xf23e; Social Skype Outline'),
        array('value' => 'ion-social-snapchat', 'content' => '&#xf4ec; Social Snapchat'),
        array('value' => 'ion-social-snapchat-outline', 'content' => '&#xf4eb; Social Snapchat Outline'),
        array('value' => 'ion-social-tumblr', 'content' => '&#xf241; Social Tumblr'),
        array('value' => 'ion-social-tumblr-outline', 'content' => '&#xf240; Social Tumblr Outline'),
        array('value' => 'ion-social-tux', 'content' => '&#xf2c5; Social Tux'),
        array('value' => 'ion-social-twitch', 'content' => '&#xf4ee; Social Twitch'),
        array('value' => 'ion-social-twitch-outline', 'content' => '&#xf4ed; Social Twitch Outline'),
        array('value' => 'ion-social-twitter', 'content' => '&#xf243; Social Twitter'),
        array('value' => 'ion-social-twitter-outline', 'content' => '&#xf242; Social Twitter Outline'),
        array('value' => 'ion-social-usd', 'content' => '&#xf353; Social Usd'),
        array('value' => 'ion-social-usd-outline', 'content' => '&#xf352; Social Usd Outline'),
        array('value' => 'ion-social-vimeo', 'content' => '&#xf245; Social Vimeo'),
        array('value' => 'ion-social-vimeo-outline', 'content' => '&#xf244; Social Vimeo Outline'),
        array('value' => 'ion-social-whatsapp', 'content' => '&#xf4f0; Social Whatsapp'),
        array('value' => 'ion-social-whatsapp-outline', 'content' => '&#xf4ef; Social Whatsapp Outline'),
        array('value' => 'ion-social-windows', 'content' => '&#xf247; Social Windows'),
        array('value' => 'ion-social-windows-outline', 'content' => '&#xf246; Social Windows Outline'),
        array('value' => 'ion-social-wordpress', 'content' => '&#xf249; Social Wordpress'),
        array('value' => 'ion-social-wordpress-outline', 'content' => '&#xf248; Social Wordpress Outline'),
        array('value' => 'ion-social-yahoo', 'content' => '&#xf24b; Social Yahoo'),
        array('value' => 'ion-social-yahoo-outline', 'content' => '&#xf24a; Social Yahoo Outline'),
        array('value' => 'ion-social-yen', 'content' => '&#xf4f2; Social Yen'),
        array('value' => 'ion-social-yen-outline', 'content' => '&#xf4f1; Social Yen Outline'),
        array('value' => 'ion-social-youtube', 'content' => '&#xf24d; Social Youtube'),
        array('value' => 'ion-social-youtube-outline', 'content' => '&#xf24c; Social Youtube Outline'),
        array('value' => 'ion-soup-can', 'content' => '&#xf4f4; Soup Can'),
        array('value' => 'ion-soup-can-outline', 'content' => '&#xf4f3; Soup Can Outline'),
        array('value' => 'ion-speakerphone', 'content' => '&#xf2b2; Speakerphone'),
        array('value' => 'ion-speedometer', 'content' => '&#xf2b3; Speedometer'),
        array('value' => 'ion-spoon', 'content' => '&#xf2b4; Spoon'),
        array('value' => 'ion-star', 'content' => '&#xf24e; Star'),
        array('value' => 'ion-stats-bars', 'content' => '&#xf2b5; Stats Bars'),
        array('value' => 'ion-steam', 'content' => '&#xf30b; Steam'),
        array('value' => 'ion-stop', 'content' => '&#xf24f; Stop'),
        array('value' => 'ion-thermometer', 'content' => '&#xf2b6; Thermometer'),
        array('value' => 'ion-thumbsdown', 'content' => '&#xf250; Thumbsdown'),
        array('value' => 'ion-thumbsup', 'content' => '&#xf251; Thumbsup'),
        array('value' => 'ion-toggle', 'content' => '&#xf355; Toggle'),
        array('value' => 'ion-toggle-filled', 'content' => '&#xf354; Toggle Filled'),
        array('value' => 'ion-transgender', 'content' => '&#xf4f5; Transgender'),
        array('value' => 'ion-trash-a', 'content' => '&#xf252; Trash A'),
        array('value' => 'ion-trash-b', 'content' => '&#xf253; Trash B'),
        array('value' => 'ion-trophy', 'content' => '&#xf356; Trophy'),
        array('value' => 'ion-tshirt', 'content' => '&#xf4f7; Tshirt'),
        array('value' => 'ion-tshirt-outline', 'content' => '&#xf4f6; Tshirt Outline'),
        array('value' => 'ion-umbrella', 'content' => '&#xf2b7; Umbrella'),
        array('value' => 'ion-university', 'content' => '&#xf357; University'),
        array('value' => 'ion-unlocked', 'content' => '&#xf254; Unlocked'),
        array('value' => 'ion-upload', 'content' => '&#xf255; Upload'),
        array('value' => 'ion-usb', 'content' => '&#xf2b8; Usb'),
        array('value' => 'ion-videocamera', 'content' => '&#xf256; Videocamera'),
        array('value' => 'ion-volume-high', 'content' => '&#xf257; Volume High'),
        array('value' => 'ion-volume-low', 'content' => '&#xf258; Volume Low'),
        array('value' => 'ion-volume-medium', 'content' => '&#xf259; Volume Medium'),
        array('value' => 'ion-volume-mute', 'content' => '&#xf25a; Volume Mute'),
        array('value' => 'ion-wand', 'content' => '&#xf358; Wand'),
        array('value' => 'ion-waterdrop', 'content' => '&#xf25b; Waterdrop'),
        array('value' => 'ion-wifi', 'content' => '&#xf25c; Wifi'),
        array('value' => 'ion-wineglass', 'content' => '&#xf2b9; Wineglass'),
        array('value' => 'ion-woman', 'content' => '&#xf25d; Woman'),
        array('value' => 'ion-wrench', 'content' => '&#xf2ba; Wrench'),
        array('value' => 'ion-xbox', 'content' => '&#xf30c; Xbox'),
    );

    return $icons;
}
