<?php
/*
Plugin Name: BytBil Anläggningar
Description: Skapa och visa Anläggningar.
Author: Sebastian Jonsson : BytBil Nordic AB
Version: 2.0.1
Author URI: http://www.bytbil.com
*/
add_action('init', 'cptui_register_my_cpt_facility');
function cptui_register_my_cpt_facility()
{
    register_post_type('facility', array(
            'label' => 'Anläggning',
            'description' => '',
            'public' => true,
            'show_ui' => true,
            'show_in_menu' => true,
            'capability_type' => 'post',
            'map_meta_cap' => true,
            'hierarchical' => false,
            'rewrite' => array('slug' => 'facility', 'with_front' => true),
            'query_var' => true,
            'supports' => array('title', 'revisions'),
            'labels' => array(
                'name' => 'Anläggningar',
                'singular_name' => 'Anläggning',
                'menu_name' => 'Anläggningar',
                'add_new' => 'Lägg till anläggning',
                'add_new_item' => 'Lägg till ny anläggning',
                'edit' => 'Redigera',
                'edit_item' => 'Redigera anläggning',
                'new_item' => 'Ny anläggning',
                'view' => 'Visa anläggning',
                'view_item' => 'Visa anläggning',
                'search_items' => 'Sök anläggning',
                'not_found' => 'Inga anläggningar hittades',
                'not_found_in_trash' => 'Inga anläggningar i papperskorgen',
                'parent' => 'Anläggningens förälder',
            )
        )
    );
}

if (function_exists('register_field_group')) {
    register_field_group(array(
        'id' => 'acf_anlaggning',
        'title' => 'Anläggning',
        'fields' => array(
            array(
                'key' => 'field_541ac22f98595',
                'label' => 'Kontaktinformation',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_541ac24d98596',
                'label' => 'Besöksadress',
                'name' => 'facility-visiting-address',
                'type' => 'google_map',
                'center_lat' => '57.718468',
                'center_lng' => '14.764942',
                'zoom' => 6,
                'height' => '',
            ),
            array(
                'key' => 'field_541ac879b4238',
                'label' => 'Använd annan Postadress',
                'name' => 'facility-use-postal-adress',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 0,
            ),
            array(
                'key' => 'field_541ac8b4b4239',
                'label' => 'Postadress',
                'name' => 'facility-other-adress',
                'type' => 'textarea',
                'conditional_logic' => array(
                    'status' => 1,
                    'rules' => array(
                        array(
                            'field' => 'field_541ac879b4238',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_541ac92cb423a',
                'label' => 'Telefonnummer',
                'name' => 'facility-phonenumbers',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_541ac952b423b',
                        'label' => 'Titel',
                        'name' => 'facility-phonenumber-title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_541ac973b423c',
                        'label' => 'Nummer',
                        'name' => 'facility-phonenumber-number',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Lägg till nummer',
            ),
            array(
                'key' => 'field_541ac996b423d',
                'label' => 'E-post',
                'name' => 'facility-emails',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_541ac9bcb423e',
                        'label' => 'Titel',
                        'name' => 'facility-email-title',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_541ac9d0b423f',
                        'label' => 'E-post',
                        'name' => 'facility-email-address',
                        'type' => 'email',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Lägg till E-post',
            ),
            array(
                'key' => 'field_541acb36b4243',
                'label' => 'Avdelningar och öppettider',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_541acb44b4244',
                'label' => 'Avdelningar',
                'name' => 'facility-departments',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_541acb80b4245',
                        'label' => 'Avdelning',
                        'name' => 'facility-department',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_541acb9cb4246',
                        'label' => 'Telefonnummer',
                        'name' => 'facility-department-phonenumber',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5411239cb4123',
                        'label' => 'Fax',
                        'name' => 'facility-department-fax',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_541acbd6b4247',
                        'label' => 'E-postadress',
                        'name' => 'facility-department-email',
                        'type' => 'email',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_541acbebb4248',
                        'label' => 'Öppettider',
                        'name' => 'facility-department-openhours',
                        'type' => 'repeater',
                        'column_width' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_541acbfeb4249',
                                'label' => 'Dag',
                                'name' => 'facility-department-openhours-day',
                                'type' => 'text',
                                'column_width' => 40,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_541acc18b424a',
                                'label' => 'Tid',
                                'name' => 'facility-department-openhours-time',
                                'type' => 'text',
                                'column_width' => 40,
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                            ),
                        ),
                        'row_min' => '',
                        'row_limit' => '',
                        'layout' => 'table',
                        'button_label' => 'Lägg till öppettid',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till avdelning',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'facility',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
}