<?php

function vc_remove_standard_elements()
{
    if (function_exists('vc_remove_element')) {
        vc_remove_element('ninja_forms_dislay_form'); # Not working as intended
        vc_remove_element('layerslider_vc');
        vc_remove_element('rev_slider_vc');
        vc_remove_element('vc_facebook');
        vc_remove_element('vc_accordion');
        vc_remove_element('vc_basic_grid');
        vc_remove_element('vc_btn');
        vc_remove_element('vc_button');
        vc_remove_element('vc_button2');
        vc_remove_element('vc_carousel');
        vc_remove_element('vc_column_text');
        vc_remove_element('vc_cta_button');
        vc_remove_element('vc_cta_button2');
        vc_remove_element('vc_cta');
        vc_remove_element('vc_customfield');
        vc_remove_element('vc_custom_heading');
        vc_remove_element('vc_empty_space');
        vc_remove_element('vc_flickr');
        vc_remove_element('vc_gallery');
        vc_remove_element('vc_gitem_animated_block');
        vc_remove_element('vc_gitem_col');
        vc_remove_element('vc_gitem_image');
        vc_remove_element('vc_gitem_post_data');
        vc_remove_element('vc_gitem_post_date');
        vc_remove_element('vc_gitem_post_excerpt');
        vc_remove_element('vc_gitem_post_meta');
        vc_remove_element('vc_gitem_post_title');
        vc_remove_element('vc_gitem_row');
        vc_remove_element('vc_gitem_zone_a');
        vc_remove_element('vc_gitem_zone_b');
        vc_remove_element('vc_gitem_zone_c');
        vc_remove_element('vc_gitem_zone');
        vc_remove_element('vc_gitem');
        vc_remove_element('vc_gmaps');
        vc_remove_element('vc_googleplus');
        vc_remove_element('vc_icon');
        vc_remove_element('vc_images_carousel');
        vc_remove_element('vc_masonry_grid');
        vc_remove_element('vc_masonry_media_grid');
        vc_remove_element('vc_media_grid');
        vc_remove_element('vc_message');
        vc_remove_element('vc_message_old');
        vc_remove_element('vc_pie');
        vc_remove_element('vc_pinterest');
        vc_remove_element('vc_posts_grid');
        vc_remove_element('vc_posts_slider');
        vc_remove_element('vc_progress_bar');
        vc_remove_element('vc_raw_html');
        vc_remove_element('vc_tab');
        vc_remove_element('vc_tabs');
        vc_remove_element('vc_teaser_grid');
        vc_remove_element('vc_text_separator');
        vc_remove_element('vc_toggle');
        vc_remove_element('vc_toggle_old');
        vc_remove_element('vc_tour');
        vc_remove_element('vc_tweetmeme');
        vc_remove_element('vc_twitter');
        vc_remove_element('vc_video');
        vc_remove_element('vc_widget_sidebar');

        // WordPress stuff
        vc_remove_element('vc_wp_search');
        vc_remove_element('vc_wp_meta');
        vc_remove_element('vc_wp_recentcomments');
        vc_remove_element('vc_wp_calendar');
        vc_remove_element('vc_wp_pages');
        vc_remove_element('vc_wp_tagcloud');
        vc_remove_element('vc_wp_custommenu');
        vc_remove_element('vc_wp_posts');
        vc_remove_element('vc_wp_categories');
        vc_remove_element('vc_wp_archives');
        vc_remove_element('vc_wp_rss');
    }
}
add_action('init', 'vc_remove_standard_elements', 1, 1);
