<?php
/*
Plugin Name: BytBil Sitesettings
Description: Ändra utseende och inställningar för mallsidor.
Author: 
Version: 2.0.2
Author URI: http://www.bytbil.com
*/
include('functions.php');

add_action('init', 'cptui_register_my_cpt_sitesettings');
function cptui_register_my_cpt_sitesettings()
{
    register_post_type('sitesettings', array(
        'label' => 'Sideinställningar',
        'description' => 'Denna innehållstyp styr de generella inställningarna för denna webbplats.',
        'public' => true,
        'show_ui' => true,
        'capability_type' => 'post',
        'map_meta_cap' => true,
        'hierarchical' => false,
        'rewrite' => array('slug' => 'sitesettings', 'with_front' => true),
        'query_var' => true,
        'supports' => array('title'),
        'labels' => array(
            'name' => 'Sidinställningar',
            'singular_name' => 'Sidinställning',
            'menu_name' => 'Hemsideinställningar',
            'add_new' => 'Lägg till inställning',
            'add_new_item' => 'Ny inställning',
            'edit' => 'Redigera hemsida',
            'edit_item' => 'Redigera hemsida',
            'new_item' => 'Ny inställning',
            'view' => 'Visa inställningar',
            'view_item' => 'Visa inställning',
            'search_items' => 'Sök inställningar',
            'not_found' => 'Inga inställningar hittades',
            'not_found_in_trash' => 'Inga inställningar i papperskorgen',
            'parent' => 'Inställningens förälder',
        )
    ));
}

add_action('init', 'cptui_register_my_cpt_settingsfooter');
function cptui_register_my_cpt_settingsfooter()
{
    register_post_type('settingsfooter', array(
        'label' => 'Sidfot',
        'desctription' => '',
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => 'edit.php?post_type=sitesettings',
        'capability_type' => 'post',
        'map_meta_cap' => true,
        'hierarchical' => false,
        'rewrite' => array('slug' => 'sidfot', 'with_front' => false),
        'query_var' => true,
        'supports' => array('title', 'revisions', 'editor'),
        'labels' => array(
            'name' => 'Sidfot',
            'singular_name' => 'Sidfot',
            'menu_name' => 'Sidfot',
            'add_new' => 'Lägg till sidfot',
            'add_new_item' => 'Ny sidfot',
            'edit' => 'Redigera sidfot',
            'edit_item' => 'Redigera sidfot',
            'new_item' => 'Ny sidfot',
            'view' => 'Visa sidfot',
            'view_item' => 'Visa sidfot',
            'search_items' => 'Sök sidfötter',
            'not_found' => 'Inga sidfötter hittades',
            'not_found_in_trash' => 'Inga sidfötter i papperskorgen',
            'parent' => 'Sidfotens förälder',
        )
    ));
}

if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_utseende',
        'title' => 'Utseende',
        'fields' => array (
            array (
                'key' => 'field_56cad7a203925',
                'label' => 'Utseende',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_57dad8e019382',
                'label' => 'Design',
                'name' => 'sitesetting-design',
                'type' => 'radio',
                'instructions' => 'Välj om du vill bred eller smal design.',
                'choices' => array (
                    'wide' => 'Bred',
                    'narrow' => 'Smal',
                ),
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => 'wide',
                'layout' => 'horizontal'
            ),
            array (
                'key' => 'field_56cad7e503926',
                'label' => 'Redigera bakgrund',
                'name' => 'sitesetting-edit-background',
                'type' => 'radio',
                'instructions' => 'Välj om du vill använda en färg eller en bild som bakgrund.',
                'choices' => array (
                    'color' => 'Färg',
                    'image' => 'Bild',
                ),
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
            ),
            array (
                'key' => 'field_56cad84703927',
                'label' => 'Bakgrundsfärg',
                'name' => 'sitesetting-background-color',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken bakgrundsfärg hemsidan skall ha.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56cad7e503926',
                            'operator' => '==',
                            'value' => 'color',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_56cad88603928',
                'label' => 'Bakgrundsbild',
                'name' => 'sitesetting-background-image',
                'type' => 'image',
                'instructions' => 'Välj eller ladda upp en bakgrundsbild som skall visas på hemsidan.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56cad7e503926',
                            'operator' => '==',
                            'value' => 'image',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_56cad9e003929',
                'label' => 'Wrapperbredd',
                'name' => 'sitesetting-wrapper-width',
                'type' => 'number',
                'default_value' => 1170,
                'placeholder' => '',
                'prepend' => '',
                'append' => 'px',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_56dad1000e929',
                'label' => 'Wrapper : Bakgrundsfärg',
                'name' => 'sitesetting-wrapper-bg-color',
                'type' => 'color_picker',
                'instructions' => 'Välj bakgrundsfärg för wrappern.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_57dad8e019382',
                            'operator' => '==',
                            'value' => 'narrow',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_56caw2001e872',
                'label' => 'Wrapper : Skugga',
                'name' => 'sitesetting-wrapper-shadow',
                'type' => 'text',
                'instructions' => 'Fyll i CSS-kod för wrapperns skugga.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_57dad8e019382',
                            'operator' => '==',
                            'value' => 'narrow',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => 'Exempel: 0px 1px 2px #333',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56cae20803939',
                'label' => 'Använd rundade hörn',
                'name' => 'sitesetting-border-radius',
                'type' => 'true_false',
                'instructions' => 'Välj om du vill att designen skall använda sig av rundade hörn.',
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_56cae29e0393a',
                'label' => 'Rundning',
                'name' => 'sitesetting-border-radius-val',
                'type' => 'number',
                'instructions' => 'Välj hur många pixlar hörnen skall rundas med.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56cae20803939',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => 5,
                'placeholder' => 'Exempel: 5 (px)',
                'prepend' => '',
                'append' => 'px',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_56cada1d0392a',
                'label' => 'Typsnitt och text',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_56cada550392b',
                'label' => 'Rubriker : Typsnitt',
                'name' => 'sitesetting-font-family-header',
                'type' => 'select',
                'instructions' => 'Välj ett typsnitt i listan som skall användas av rubriker på sidan.',
                'choices' => array (
                    'open_sansregular' => 'Open Sans',
                    'Arial' => 'Arial',
                    'Helvetica' => 'Helvetica',
                    'Georgia' => 'Georgia',
                    'Arvo' => 'Arvo',
                    'Slabo 27px' => 'Slabo',
                    'Lato' => 'Lato',
                    'Roboto' => 'Roboto',
                    'Kelly Slab' => 'Kelly',
                    'Arbutus Slab' => 'Arbutus Slab',
                    'other' => 'Annat',
                ),
                'default_value' => 'Open Sans',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_56cadb170392c',
                'label' => 'Rubriker : Storlek',
                'name' => 'sitesetting-font-size-header',
                'type' => 'number',
                'instructions' => 'Välj vilken storlek rubrikerna på din hemsida skall ha.',
                'default_value' => 36,
                'placeholder' => 'Ex: 36 (pt)',
                'prepend' => '',
                'append' => 'pt',
                'min' => 1,
                'max' => 150,
                'step' => 1,
            ),
            array (
                'key' => 'field_56cadb9d0392d',
                'label' => 'Rubriker : Färg',
                'name' => 'sitesetting-font-color-header',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken färg hemsidans rubriker skall ha.',
                'default_value' => '#222222',
            ),
            array (
                'key' => 'field_56cadbce0392e',
                'label' => '@import-länk',
                'name' => 'sitesetting-font-other-import',
                'type' => 'text',
                'instructions' => 'Klistra in @import länken här.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56cada550392b',
                            'operator' => '==',
                            'value' => 'other',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '@import url(...)',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56cadc310392f',
                'label' => 'Fontnamn',
                'name' => 'sitesetting-font-other-name',
                'type' => 'text',
                'instructions' => 'Namnet som skrivs in i CSSen.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56cada550392b',
                            'operator' => '==',
                            'value' => 'other',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '\'Open Sans\', sans-serif',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56cadc7a03930',
                'label' => 'Vart gäller denna font?',
                'name' => 'sitesetting-font-other-locations',
                'type' => 'checkbox',
                'instructions' => 'På vilka delar av siten skall custom-fonten gälla?',
                'choices' => array (
                    'headers' => 'Rubriker',
                    'paragraphs' => 'Brödtext',
                    'menuTopLevel' => 'Toppnivå menyer',
                    'menuSubMenu' => 'Undernivå menyer',
                ),
                'default_value' => 'headers',
                'layout' => 'horizontal',
            ),
            array (
                'key' => 'field_56cadd2803931',
                'label' => 'Text : Typsnitt',
                'name' => 'sitesetting-font-family-paragraph',
                'type' => 'select',
                'instructions' => 'Välj ett typsnitt i listan som skall användas av brödtext på sidan.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56cadc7a03930',
                            'operator' => '!=',
                            'value' => '',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    'Open Sans' => 'Open Sans',
                    'Arial' => 'Arial',
                    'Helvetica' => 'Helvetica',
                    'Georgia' => 'Georgia',
                    'Arvo' => 'Arvo',
                    'Slabo 13px' => 'Slabo',
                    'Lato' => 'Lato',
                    'Roboto' => 'Roboto',
                    'Kelly Slab' => 'Kelly',
                    'Arbutus Slab' => 'Arbutus Slab',
                ),
                'default_value' => 'Open Sans',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_56caddc903932',
                'label' => 'Text : Storlek',
                'name' => 'sitesetting-font-size-paragraph',
                'type' => 'number',
                'instructions' => 'Välj vilken storlek texten på din hemsida ska ha.',
                'default_value' => 14,
                'placeholder' => 'Ex: 14 (pt)',
                'prepend' => '',
                'append' => 'pt',
                'min' => 1,
                'max' => 150,
                'step' => 1,
            ),
            array (
                'key' => 'field_56cade0703933',
                'label' => 'Text : Färg',
                'name' => 'sitesetting-font-color-paragraph',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken färg hemsidans brödtext skall ha.',
                'default_value' => '#111111',
            ),
            array (
                'key' => 'field_56cade4003934',
                'label' => 'Länkinställningar',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_56cade5f03935',
                'label' => 'Länkfärg',
                'name' => 'sitesetting-link-color',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken färg en länk skall ha på sidan.',
                'default_value' => '#2b58ae',
            ),
            array (
                'key' => 'field_56cadea103936',
                'label' => 'Länkeffekt',
                'name' => 'sitesetting-link-effect',
                'type' => 'checkbox',
                'instructions' => 'Välj om du vill ha någon texteffekt på länken.',
                'choices' => array (
                    'underline' => 'Understruken',
                    'bold' => 'Fetstil',
                ),
                'default_value' => '',
                'layout' => 'horizontal',
            ),
            array (
                'key' => 'field_56cadedb03937',
                'label' => 'Länkfärg : Hover',
                'name' => 'sitesetting-link-color-hover',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken färg en länk får när man har muspekaren över.',
                'default_value' => '#2f5db4',
            ),
            array (
                'key' => 'field_56cadf3b03938',
                'label' => 'Länkeffekt : Hover',
                'name' => 'sitesetting-link-effect-hover',
                'type' => 'checkbox',
                'instructions' => 'Välj om du vill ha någon texteffekt på länken.',
                'choices' => array (
                    'underline' => 'Understruken',
                    'bold' => 'Fetstil',
                ),
                'default_value' => '',
                'layout' => 'horizontal',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sitesettings',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_menyer',
        'title' => 'Menyer',
        'fields' => array (
            array (
                'key' => 'field_56cae3a3d7f2a',
                'label' => 'Huvudmeny',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_56cae3e2d7f2b',
                'label' => 'Typsnitt',
                'name' => 'sitesetting-menus-font-family',
                'type' => 'select',
                'instructions' => 'Välj ett typsnitt i listan som skall användas av huvudmenyn på sidan.',
                'choices' => array (
                    'Open Sans' => 'Open Sans',
                    'Arial' => 'Arial',
                    'Helvetica' => 'Helvetica',
                    'Georgia' => 'Georgia',
                    'Arvo' => 'Arvo',
                    'Slabo 13px' => 'Slabo',
                    'Lato' => 'Lato',
                    'Roboto' => 'Roboto',
                    'Kelly Slab' => 'Kelly',
                    'Arbutus Slab' => 'Arbutus Slab',
                ),
                'default_value' => 'Open Sans',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_56cae463d7f2c',
                'label' => 'Textstorlek',
                'name' => 'sitesetting-menus-font-size',
                'type' => 'number',
                'instructions' => 'Välj vilken typsnittsstorlek som skall användas i huvudmenyn.',
                'default_value' => 14,
                'placeholder' => 'Ex: 14 (pt)',
                'prepend' => '',
                'append' => 'pt',
                'min' => 1,
                'max' => 150,
                'step' => 1,
            ),
            array (
                'key' => 'field_56cae49cd7f2d',
                'label' => 'Menyfärg',
                'name' => 'sitesetting-menus-background',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken bakgrundsfärg som det skall vara på menyn.',
                'default_value' => '#333333',
            ),
            array (
                'key' => 'field_56cae4c7d7f2e',
                'label' => 'Effekter',
                'name' => 'sitesetting-menus-settings',
                'type' => 'checkbox',
                'instructions' => 'Redigera inställningar för menyn.',
                'choices' => array (
                    'shadow' => 'Skugga',
                    'border' => 'Kantlinje',
                    'caps' => 'Stora bokstäver',
                    'hover' => 'Undermeny vid hover',
                ),
                'default_value' => '',
                'layout' => 'horizontal',
            ),
            array (
                'key' => 'field_56cae51ad7f2f',
                'label' => 'Kantlinje',
                'name' => 'sitesetting-menus-border',
                'type' => 'text',
                'instructions' => 'Fyll i CSS-kod för menyns kantlinje.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56cae4c7d7f2e',
                            'operator' => '==',
                            'value' => 'border',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => 'Exempel: 1px solid #ddd',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56cae562d7f30',
                'label' => 'Skugga',
                'name' => 'sitesetting-menus-shadow',
                'type' => 'text',
                'instructions' => 'Fyll i CSS-kod för menyns skugga.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56cae4c7d7f2e',
                            'operator' => '==',
                            'value' => 'shadow',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => 'Exempel: 0px 1px 2px #333',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56cae5a0d7f31',
                'label' => 'Länkfärg',
                'name' => 'sitesetting-menus-link-color',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken färg länken skall ha.',
                'default_value' => '#ffffff',
            ),
            array (
                'key' => 'field_56cae5efd7f32',
                'label' => 'Bakgrundsfärg',
                'name' => 'sitesetting-menus-link-bgcolor',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken bakgrundsfärg länken skall ha.',
                'default_value' => '#ffffff',
            ),
            array (
                'key' => 'field_56cae658d7f33',
                'label' => 'Länkeffekt',
                'name' => 'sitesetting-menus-link-effect',
                'type' => 'checkbox',
                'instructions' => 'Välj om du vill ha någon texteffekt på länken.',
                'choices' => array (
                    'underline' => 'Understruken',
                    'bold' => 'Fetstil',
                ),
                'default_value' => '',
                'layout' => 'horizontal',
            ),
            array (
                'key' => 'field_56cae6d4d7f34',
                'label' => 'Länkfärg : Hover',
                'name' => 'sitesetting-menus-link-color-hover',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken färg länken skall ha när man håller muspekaren över.',
                'default_value' => '#ffffff',
            ),
            array (
                'key' => 'field_56cae70bd7f35',
                'label' => 'Bakgrundsfärg : Hover',
                'name' => 'sitesetting-menus-link-bgcolor-hover',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken bakgrundsfärg länken skall ha när man håller muspekaren över.',
                'default_value' => '#ffffff',
            ),
            array (
                'key' => 'field_56cae73cd7f36',
                'label' => 'Länkeffekt : Hover',
                'name' => 'sitesetting-menus-link-effect-hover',
                'type' => 'checkbox',
                'instructions' => 'Välj om du vill ha någon texteffekt på länken när man håller muspekaren över.',
                'choices' => array (
                    'underline' => 'Understruken',
                    'bold' => 'Fetstil',
                ),
                'default_value' => '',
                'layout' => 'horizontal',
            ),
            array (
                'key' => 'field_56cae78bd7f37',
                'label' => 'Undermeny',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_56cae7d6d7f38',
                'label' => 'Typsnitt',
                'name' => 'sitesetting-submenus-font-family',
                'type' => 'select',
                'instructions' => 'Välj ett typsnitt i listan som skall användas i undermenyn.',
                'choices' => array (
                    'Open Sans' => 'Open Sans',
                    'Arial' => 'Arial',
                    'Helvetica' => 'Helvetica',
                    'Georgia' => 'Georgia',
                    'Arvo' => 'Arvo',
                    'Slabo 13px' => 'Slabo',
                    'Lato' => 'Lato',
                    'Roboto' => 'Roboto',
                    'Kelly Slab' => 'Kelly',
                    'Arbutus Slab' => 'Arbutus Slab',
                ),
                'default_value' => 'Open Sans',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_56cae831d7f39',
                'label' => 'Textstorlek',
                'name' => 'sitesetting-submenus-font-size',
                'type' => 'number',
                'instructions' => 'Välj vilken typsnittsstorlek som skall användas i undermenyn.',
                'default_value' => 14,
                'placeholder' => 'Ex: 14 (pt)',
                'prepend' => '',
                'append' => 'pt',
                'min' => 1,
                'max' => 150,
                'step' => 1,
            ),
            array (
                'key' => 'field_56cae890d7f3a',
                'label' => 'Menyfärg',
                'name' => 'sitesetting-submenus-background',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken färg undermenyn skall ha.',
                'default_value' => '#111111',
            ),
            array (
                'key' => 'field_56caec30d7f3b',
                'label' => 'Länkfärg',
                'name' => 'sitesetting-submenus-link-color',
                'type' => 'color_picker',
                'default_value' => '#ffffff',
            ),
            array (
                'key' => 'field_56caec7fd7f3c',
                'label' => 'Bakgrundsfärg',
                'name' => 'sitesetting-submenus-link-bgcolor',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken bakgrundsfärg som länken skall ha.',
                'default_value' => 'transparent',
            ),
            array (
                'key' => 'field_56caed25d7f3d',
                'label' => 'Länkeffekt',
                'name' => 'sitesetting-submenus-link-effect',
                'type' => 'checkbox',
                'instructions' => 'Välj om du vill ha någon texteffekt på länken.',
                'choices' => array (
                    'underline' => 'Understruken',
                    'bold' => 'Fetstil',
                    'ucase' => 'Stora bokstäver',
                ),
                'default_value' => '',
                'layout' => 'horizontal',
            ),
            array (
                'key' => 'field_56caedadd7f3e',
                'label' => 'Länkfärg : Hover',
                'name' => 'sitesetting-submenus-link-color-hover',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken textfärg länken i en undermeny skall ha när man för muspekaren över.',
                'default_value' => '#ffffff',
            ),
            array (
                'key' => 'field_56caee2cd7f3f',
                'label' => 'Bakgrundsfärg : Hover',
                'name' => 'sitesetting-submenus-link-bgcolor-hover',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken bakgrundsfärg länken skall ha när man håller muspekaren över.',
                'default_value' => '#111111',
            ),
            array (
                'key' => 'field_56caee71d7f40',
                'label' => 'Länkeffekt : Hover',
                'name' => 'sitesetting-submenus-link-effect-hover',
                'type' => 'checkbox',
                'instructions' => 'Välj om du vill ha någon texteffekt på länken när man håller muspekaren över.',
                'choices' => array (
                    'underline' => 'Understruken',
                    'bold' => 'Fetstil',
                ),
                'default_value' => '',
                'layout' => 'horizontal',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sitesettings',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 1,
    ));
    register_field_group(array (
        'id' => 'acf_sidhuvud',
        'title' => 'Sidhuvud',
        'fields' => array (
            array (
                'key' => 'field_56caf1e10cacc',
                'label' => 'Logotyp',
                'name' => 'sitesetting-logotype',
                'type' => 'image',
                'instructions' => 'Ladda upp en bild på er logotyp som skall visas på hemsidan.',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_56caf2510cacd',
                'label' => 'Kolumnbredd för logotyp',
                'name' => 'sitesetting-header-columns',
                'type' => 'select',
                'choices' => array (
                    3 => '25%',
                    4 => '33%',
                    6 => '50%',
                    8 => '66%',
                    12 => '100%',
                ),
                'default_value' => 6,
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_56caf2b50cace',
                'label' => 'Favicon',
                'name' => 'sitesetting-header-favicon',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_56caf2d80cacf',
                'label' => 'Bakgrundsfärg',
                'name' => 'sitesetting-header-bgcolor',
                'type' => 'color_picker',
                'instructions' => 'Välj vilken färg du vill ha på sidhuvudet.',
                'default_value' => '#ffffff',
            ),
            array (
                'key' => 'field_56caf30a0cad0',
                'label' => 'Genomskinlighet på sidhuvudets bakgrundsfärg',
                'name' => 'sitesetting-header-opacity',
                'type' => 'number',
                'instructions' => 'Genomskinlighet.',
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '%',
                'min' => 0,
                'max' => 100,
                'step' => 1,
            ),
            array (
                'key' => 'field_56caf3650cad1',
                'label' => 'Egen kod',
                'name' => 'sitesetting-custom-code',
                'type' => 'checkbox',
                'instructions' => 'Välj om du vill infoga egen kod i sidhuvudet på hemsidan.',
                'choices' => array (
                    'css' => 'CSS',
                    'javascript' => 'JavaScript',
                ),
                'default_value' => '',
                'layout' => 'horizontal',
            ),
            array (
                'key' => 'field_56caf3be0cad2',
                'label' => 'CSS-kod',
                'name' => 'sitesetting-custom-code-css',
                'type' => 'code_area',
                'instructions' => 'Fyll i CSS som du vill skall läsas in i sidhuvudet på hemsidan.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56caf3650cad1',
                            'operator' => '==',
                            'value' => 'css',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'language' => 'css',
                'theme' => 'solarized',
            ),
            array (
                'key' => 'field_56caf3f40cad3',
                'label' => 'JavaScript-kod',
                'name' => 'sitesetting-custom-code-js',
                'type' => 'code_area',
                'instructions' => 'Fyll i JavaScript som du vill skall läsas in i sidhuvudet på hemsidan.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56caf3650cad1',
                            'operator' => '==',
                            'value' => 'javascript',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'language' => 'javascript',
                'theme' => 'solarized',
            ),
            array (
                'key' => 'field_56caf4d3229c1',
                'label' => 'Märken',
                'name' => 'sitesetting-brands',
                'type' => 'relationship',
                'post_type' => array(
                    0 => 'brand',
                ),
                'taxonomy' => array(
                    0 => 'all',
                ),
                'filters' => array(
                    0 => 'search',
                ),
                'result_elements' => array(
                    0 => 'post_title',
                ),
                'max' => '',
            ),
            array (
                'key' => 'field_56caf5e5229c1',
                'label' => 'Snabblänkar',
                'name' => 'sitesetting-header-shortlinks',
                'type' => 'repeater',
                'instructions' => 'Lägg till snabblänkar som visas i sidhuvudet.',
                'sub_fields' => array (
                    array (
                        'key' => 'field_56caf60d229c2',
                        'label' => 'Länktext',
                        'name' => 'sitesetting-header-shortlink-text',
                        'type' => 'text',
                        'instructions' => 'Ange en text som skall stå i länken.',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'Exempel: Lär mer eller kontakta oss',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_56caf645229c3',
                        'label' => 'Länktyp',
                        'name' => 'sitesetting-header-shortlink-type',
                        'type' => 'select',
                        'instructions' => 'Välj vilken typ av länk.',
                        'column_width' => '',
                        'choices' => array (
                            'internal' => 'Lokal sida',
                            'external' => 'Extern URL',
                            'phone' => 'Telefonnummer',
                            'email' => 'E-postaddress',
                        ),
                        'default_value' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array (
                        'key' => 'field_56caf6ad229c4',
                        'label' => 'Lokal sida',
                        'name' => 'sitesetting-header-shortlink-page',
                        'type' => 'page_link',
                        'instructions' => 'Välj vilken sida länken skall gå till.',
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf645229c3',
                                    'operator' => '==',
                                    'value' => 'internal',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'post_type' => array (
                            0 => 'page',
                            1 => 'offer',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array (
                        'key' => 'field_56caf6e8229c5',
                        'label' => 'Extern URL',
                        'name' => 'sitesetting-header-shortlink-url',
                        'type' => 'text',
                        'instructions' => 'Ange addressen som länken skall gå till.',
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf645229c3',
                                    'operator' => '==',
                                    'value' => 'external',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'Exempel: http://www.mercedes-benz.se',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_56caf75a5ece2',
                        'label' => 'Länkbeteende',
                        'name' => 'sitesetting-header-shortlink-target',
                        'type' => 'select',
                        'instructions' => 'Välj hur du vill att länken skall öppnas.',
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf645229c3',
                                    'operator' => '==',
                                    'value' => 'internal',
                                ),
                                array (
                                    'field' => 'field_56caf645229c3',
                                    'operator' => '==',
                                    'value' => 'external',
                                ),
                            ),
                            'allorany' => 'any',
                        ),
                        'column_width' => '',
                        'choices' => array (
                            '_self' => 'Öppna i samma fönster',
                            '_blank' => 'Öppna i nytt fönster',
                            'lightbox' => 'Öppna i en lightbox',
                        ),
                        'default_value' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array (
                        'key' => 'field_56caf7cc5ece4',
                        'label' => 'Telefonnummer',
                        'name' => 'sitesetting-header-shortlink-phone',
                        'type' => 'text',
                        'instructions' => 'Ange telefonnumret som länken skall gå till.',
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf645229c3',
                                    'operator' => '==',
                                    'value' => 'phone',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'Exempel: 0701234567',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_56caf8035ece5',
                        'label' => 'E-post',
                        'name' => 'sitesetting-header-shortlink-email',
                        'type' => 'text',
                        'instructions' => 'Ange epostaddressen som länken skall gå till.',
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf645229c3',
                                    'operator' => '==',
                                    'value' => 'email',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => 'Exempel: info@autoking.se',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_56caf8685ece6',
                        'label' => 'Redigera utseende',
                        'name' => 'sitesetting-header-shortlink-appearance',
                        'type' => 'true_false',
                        'column_width' => '',
                        'message' => '',
                        'default_value' => 0,
                    ),
                    array (
                        'key' => 'field_56caf88b5ece7',
                        'label' => 'Bakgrund',
                        'name' => 'sitesetting-header-shortlink-bgcolor',
                        'type' => 'color_picker',
                        'instructions' => 'Välj vilken bakgrundsfärg som länken skall ha.',
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf8685ece6',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '#cccccc',
                    ),
                    array (
                        'key' => 'field_56caf8b65ece8',
                        'label' => 'Bakgrund : Hover',
                        'name' => 'sitesetting-header-shortlink-bgcolor-hover',
                        'type' => 'color_picker',
                        'instructions' => 'Välj vilken bakgrundsfärg som länken skall ha när man håller muspekaren över.',
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf8685ece6',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '#dddddd',
                    ),
                    array (
                        'key' => 'field_56caf8e55ece9',
                        'label' => 'Textfärg',
                        'name' => 'sitesetting-header-shortlink-color',
                        'type' => 'color_picker',
                        'instructions' => 'Välj vilken färg som länktexten skall ha',
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf8685ece6',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '#333333',
                    ),
                    array (
                        'key' => 'field_56caf9275ecea',
                        'label' => 'Textfärg : Hover',
                        'name' => 'sitesetting-header-shortlink-color-hover',
                        'type' => 'color_picker',
                        'instructions' => 'Välj vilken färg som länktexten skall ha när man håller muspekaren över.',
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf8685ece6',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                        'column_width' => '',
                        'default_value' => '#333333',
                    ),
                    array (
                        'key' => 'field_56d5bcfa92e05',
                        'label' => 'Ikon',
                        'name' => 'sitesetting-header-shortlink-icon',
                        'type' => 'ionicons',
                        'instructions' => 'Välj en ikon som skall visas bredvid med länken.',
                        'allow_null' => 1,
                        'conditional_logic' => array (
                            'status' => 1,
                            'rules' => array (
                                array (
                                    'field' => 'field_56caf8685ece6',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                            'allorany' => 'all',
                        ),
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Lägg till snabblänk',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sitesettings',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 2,
    ));
    register_field_group(array (
        'id' => 'acf_sidfot',
        'title' => 'Sidfot',
        'fields' => array (
            array (
                'key' => 'field_56cd8bbf23840',
                'label' => 'Sidfot',
                'name' => 'sitesetting-footer',
                'type' => 'post_object',
                'instructions' => 'Välj en sidfot som du vill visa på alla sidor.',
                'post_type' => array (
                    0 => 'settingsfooter',
                ),
                'taxonomy' => array (
                    0 => 'all',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sitesettings',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 3,
    ));
    register_field_group(array (
        'id' => 'acf_seo',
        'title' => 'SEO',
        'fields' => array (
            array (
                'key' => 'field_56cafde4ea5c5',
                'label' => 'Titeltag',
                'name' => 'sitesetting-title-tag',
                'type' => 'text',
                'instructions' => 'Skriv över sidans standard Titel-tag',
                'default_value' => '',
                'placeholder' => 'Exempel: Autoking - Mesta bilhandlaren i Stockholm!',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56cafe18ea5c6',
                'label' => 'META Description',
                'name' => 'sitesetting-meta-description',
                'type' => 'textarea',
                'instructions' => 'Fyll i en egen description för webbsidan.',
                'default_value' => '',
                'placeholder' => 'Exempel: Stockholms främsta bilhandlare - Nya Mercedes-Benz, BMW och Audi.',
                'maxlength' => 160,
                'rows' => 3,
                'formatting' => 'none',
            ),
            array (
                'key' => 'field_56cafe6eea5c7',
                'label' => 'META Keywords',
                'name' => 'sitesetting-meta-keywords',
                'type' => 'text',
                'instructions' => 'Fyll i ett antal relevanta keywords som beskriver er hemsida. Separera med kommatecken (,).',
                'default_value' => '',
                'placeholder' => 'Exempel: (Nya bilar, Stockholm, Mercedes-Benz, Audi, BMW)',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sitesettings',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 4,
    ));
    register_field_group(array (
        'id' => 'acf_formular',
        'title' => 'Formulär',
        'fields' => array (
            array (
                'key' => 'field_56ced36b787b5',
                'label' => 'Fält',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_56ced379787b6',
                'label' => 'Border för inputfält',
                'name' => 'sitesetting-forms-inputs-border',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '1px solid #333',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56ced3b0787b7',
                'label' => 'Använd global border-radius',
                'name' => 'sitesetting-forms-border-radius-global',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_56ced402787b8',
                'label' => 'Border-radius',
                'name' => 'sitesetting-forms-border-radius',
                'type' => 'number',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56ced3b0787b7',
                            'operator' => '!=',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'px',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_56ced439787b9',
                'label' => 'Textfärg',
                'name' => 'sitesetting-forms-input-text-color',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_56ced4ab787ba',
                'label' => 'Färg placeholder-text',
                'name' => 'sitesetting-forms-placeholder-color',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_56ced4dd787bb',
                'label' => 'Knappar',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_56ced4f5787bc',
                'label' => 'Bakgrundsfärg knappar',
                'name' => 'sitesetting-forms-buttons-bgc',
                'type' => 'color_picker',
                'instructions' => 'Gäller input: submit och button',
                'default_value' => '',
            ),
            array (
                'key' => 'field_56ced51e787bd',
                'label' => 'Textfärg knappar',
                'name' => 'sitesetting-forms-buttons-color',
                'type' => 'color_picker',
                'instructions' => 'Gäller input: submit och button',
                'default_value' => '',
            ),
            array (
                'key' => 'field_56ced55d787be',
                'label' => 'Border för knappar',
                'name' => 'sitesetting-forms-buttons-border',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '1px solid #333',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sitesettings',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 5,
    ));
}
